//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Metalogix.Jobs.Reporting.CommandLine.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Metalogix.Jobs.Reporting.CommandLine.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The arguments passed to the command are not correctly formatted..
        /// </summary>
        internal static string ArgumentExceptionText {
            get {
                return ResourceManager.GetString("ArgumentExceptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EXPORTJOBHISTORYTOEXCEL [/O:outputdirectorypath] [/F:outputFileName] [/W:overwrite] [/J:jobsids] [/T:dbtype] [/I:sqlcedbfilepath]|[/N:servername /D:databasename [/A:authtype] [/U:username] [/P:password]] 
        ///
        /// /O:   Directory where Excel Report should be created. If not specified file will be created in the current directory. 
        /// /F:   Name of new Excel file. The file name must include the &quot;.xlsx&quot; extension. If no name is provided the file will be named &quot;JobHistory.xlsx&quot;.
        /// /W:   Indicates whether to overwrit [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CommandUsage {
            get {
                return ResourceManager.GetString("CommandUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Detail: {0}.
        /// </summary>
        internal static string ErrorDetail {
            get {
                return ResourceManager.GetString("ErrorDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Complete: {0}.
        /// </summary>
        internal static string ExportComplete {
            get {
                return ResourceManager.GetString("ExportComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exporting Job History to {0} in {1}.
        /// </summary>
        internal static string ExportingJobHistory {
            get {
                return ResourceManager.GetString("ExportingJobHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Started: {0}.
        /// </summary>
        internal static string ExportStarted {
            get {
                return ResourceManager.GetString("ExportStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occured while exporting the data to Excel..
        /// </summary>
        internal static string GeneralErrorText {
            get {
                return ResourceManager.GetString("GeneralErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}% Complete.
        /// </summary>
        internal static string PercentageComplete {
            get {
                return ResourceManager.GetString("PercentageComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing Log Items....
        /// </summary>
        internal static string ProcessingLogItems {
            get {
                return ResourceManager.GetString("ProcessingLogItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving Excel Report....
        /// </summary>
        internal static string SavingExcelReport {
            get {
                return ResourceManager.GetString("SavingExcelReport", resourceCulture);
            }
        }
    }
}
