//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Metalogix.Actions.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Metalogix.Actions.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} was passed a parameter of the wrong type. Expected {1}  Actual {2}.
        /// </summary>
        public static string ActionOperationBadParameter {
            get {
                return ResourceManager.GetString("ActionOperationBadParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is missing parameters.
        /// </summary>
        public static string ActionOperationMissingParameter {
            get {
                return ResourceManager.GetString("ActionOperationMissingParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;xsl:stylesheet version=&quot;1.0&quot; xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot;&gt;&lt;xsl:output method=&quot;text&quot; omit-xml-declaration=&quot;yes&quot; indent=&quot;yes&quot;/&gt;&lt;xsl:strip-space elements=&quot;*&quot;/&gt;&lt;xsl:template match=&quot;/Action&quot;&gt;&lt;xsl:param name=&quot;description&quot; select=&quot;./@ActionType&quot;/&gt;  &lt;xsl:text&gt;Action : &lt;/xsl:text&gt;&lt;xsl:value-of select=&quot;substring-before($description,&apos;,&apos;)&quot;/&gt;&lt;xsl:apply-templates/&gt;&lt;/xsl:template&gt;&lt;xsl:template match=&quot;*&quot;&gt;&lt;xsl:if test= &quot;not(@Type = &apos;System.String&apos;)&quot;&gt;&lt;xsl:text&gt;, &lt;/xsl:text&gt;&lt;xsl:value-of select=&quot;name()&quot;/&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ActionOptionsXmlToTextTransform {
            get {
                return ResourceManager.GetString("ActionOptionsXmlToTextTransform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of retries have exceeded. ({0} retries).
        /// </summary>
        public static string ActionUtils_TryThenThrowIfFail_MaxTriesReached {
            get {
                return ResourceManager.GetString("ActionUtils_TryThenThrowIfFail_MaxTriesReached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applying Configuration.
        /// </summary>
        public static string ApplyConfiguration {
            get {
                return ResourceManager.GetString("ApplyConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Azure AD Graph API Credentials for the target SPO connection have been specified. Please disconnect and reconnect to your target SharePoint and specify valid credentials..
        /// </summary>
        public static string AzureAdGraphCredentialsInvalidMessage {
            get {
                return ResourceManager.GetString("AzureAdGraphCredentialsInvalidMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azure AD Graph API Credentials for the target SPO connection have not been specified. These are required when using the Azure Office 365 Upload option. Please disconnect and reconnect to your target SharePoint and specify these additional credentials..
        /// </summary>
        public static string AzureAdGraphCredentialsNotFoundMessage {
            get {
                return ResourceManager.GetString("AzureAdGraphCredentialsNotFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Azure connection string is detected in the EnvironmentalSettings.xml file OR Configuration Database. 
        ///Please select the “Encrypt Azure/SPO Container Jobs” checkbox to use the SPO Containers OR provide a valid Azure connection string inside the EnvironmentalSettings.xml file OR Configuration Database..
        /// </summary>
        public static string AzureConnectionStringWarning {
            get {
                return ResourceManager.GetString("AzureConnectionStringWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you wish to cancel this action?.
        /// </summary>
        public static string CancelActionConfirmation {
            get {
                return ResourceManager.GetString("CancelActionConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CancelButtonText {
            get {
                return ResourceManager.GetString("CancelButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot run action. One or more sources are also targets..
        /// </summary>
        public static string CannotRunOneOrMoreSourcesAlsoTarget {
            get {
                return ResourceManager.GetString("CannotRunOneOrMoreSourcesAlsoTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot run action. The target is the same as the source..
        /// </summary>
        public static string CannotRunTargetIsSameAsSource {
            get {
                return ResourceManager.GetString("CannotRunTargetIsSameAsSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string CloseButtonText {
            get {
                return ResourceManager.GetString("CloseButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you would like to apply the selected job configuration? The current configuration will be lost..
        /// </summary>
        public static string ConfirmActionTemplateApplication {
            get {
                return ResourceManager.GetString("ConfirmActionTemplateApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are trying to apply a job configuration that was saved in Advanced Mode. Any advanced options that are not available in Simplified Mode may not be set correctly..
        /// </summary>
        public static string ConfirmActionTemplateApplication_AdvancedToSimplified {
            get {
                return ResourceManager.GetString("ConfirmActionTemplateApplication_AdvancedToSimplified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CURRENTLY RUNNING.
        /// </summary>
        public static string CurrentlyRunningTabName {
            get {
                return ResourceManager.GetString("CurrentlyRunningTabName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string DetailsButtonText {
            get {
                return ResourceManager.GetString("DetailsButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EnableCustomTransformers.
        /// </summary>
        public static string EnableCustomTransformersKey {
            get {
                return ResourceManager.GetString("EnableCustomTransformersKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to locate action sources. This may be because they have been deleted..
        /// </summary>
        public static string FailedToLocateActionSources {
            get {
                return ResourceManager.GetString("FailedToLocateActionSources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to locate action targets. This may be because they have been deleted..
        /// </summary>
        public static string FailedToLocateActionTargets {
            get {
                return ResourceManager.GetString("FailedToLocateActionTargets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FileMappingDBContext.
        /// </summary>
        public static string FileMappingDBContextKey {
            get {
                return ResourceManager.GetString("FileMappingDBContextKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any part of Field.
        /// </summary>
        public static string FindAndReplaceOperand_Contains {
            get {
                return ResourceManager.GetString("FindAndReplaceOperand_Contains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End of Field.
        /// </summary>
        public static string FindAndReplaceOperand_EndsWith {
            get {
                return ResourceManager.GetString("FindAndReplaceOperand_EndsWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whole Field.
        /// </summary>
        public static string FindAndReplaceOperand_Equals {
            get {
                return ResourceManager.GetString("FindAndReplaceOperand_Equals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regular Expression.
        /// </summary>
        public static string FindAndReplaceOperand_RegEx {
            get {
                return ResourceManager.GetString("FindAndReplaceOperand_RegEx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start of Field.
        /// </summary>
        public static string FindAndReplaceOperand_StartsWith {
            get {
                return ResourceManager.GetString("FindAndReplaceOperand_StartsWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot identify a valid license to run this action..
        /// </summary>
        public static string Invalid_License {
            get {
                return ResourceManager.GetString("Invalid_License", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JobTemplateResolver.
        /// </summary>
        public static string JobTemplateResolver {
            get {
                return ResourceManager.GetString("JobTemplateResolver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Migrated.
        /// </summary>
        public static string License_Used {
            get {
                return ResourceManager.GetString("License_Used", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only a single action source could be located. This may be because one or more sources have been deleted..
        /// </summary>
        public static string OnlySingleActionSourceCouldBeLocated {
            get {
                return ResourceManager.GetString("OnlySingleActionSourceCouldBeLocated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only a single action target could be located. This may be because one or more targets have been deleted..
        /// </summary>
        public static string OnlySingleActionTargetCouldBeLocated {
            get {
                return ResourceManager.GetString("OnlySingleActionTargetCouldBeLocated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PerActionResourceUse.
        /// </summary>
        public static string PerActionResourceUseKey {
            get {
                return ResourceManager.GetString("PerActionResourceUseKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PercentageCPUUsage.
        /// </summary>
        public static string PercentageCPUUsageKey {
            get {
                return ResourceManager.GetString("PercentageCPUUsageKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RemotePowerShellScriptFilesLocation.
        /// </summary>
        public static string RemotePowerShellScriptFilesLocationKey {
            get {
                return ResourceManager.GetString("RemotePowerShellScriptFilesLocationKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RemotePowerShellTimerInterval.
        /// </summary>
        public static string RemotePowerShellTimerIntervalKey {
            get {
                return ResourceManager.GetString("RemotePowerShellTimerIntervalKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQLMappingDBContext.
        /// </summary>
        public static string SQLMappingDBContextKey {
            get {
                return ResourceManager.GetString("SQLMappingDBContextKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aborted.
        /// </summary>
        public static string StatusLabel_Aborted {
            get {
                return ResourceManager.GetString("StatusLabel_Aborted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        public static string StatusLabel_Completed {
            get {
                return ResourceManager.GetString("StatusLabel_Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed with a Warning.
        /// </summary>
        public static string StatusLabel_CompletedWithWarning {
            get {
                return ResourceManager.GetString("StatusLabel_CompletedWithWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed.
        /// </summary>
        public static string StatusLabel_Failed {
            get {
                return ResourceManager.GetString("StatusLabel_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Migration Aborted.
        /// </summary>
        public static string StatusLabel_MigrationAborted {
            get {
                return ResourceManager.GetString("StatusLabel_MigrationAborted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Migration Completed.
        /// </summary>
        public static string StatusLabel_MigrationComplete {
            get {
                return ResourceManager.GetString("StatusLabel_MigrationComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Migration Completed with a Warning.
        /// </summary>
        public static string StatusLabel_MigrationCompletedWithWarning {
            get {
                return ResourceManager.GetString("StatusLabel_MigrationCompletedWithWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Migration Failed.
        /// </summary>
        public static string StatusLabel_MigrationFailed {
            get {
                return ResourceManager.GetString("StatusLabel_MigrationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preparing to Run Migration.
        /// </summary>
        public static string StatusLabel_MigrationNotRunning {
            get {
                return ResourceManager.GetString("StatusLabel_MigrationNotRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Migration Paused.
        /// </summary>
        public static string StatusLabel_MigrationPaused {
            get {
                return ResourceManager.GetString("StatusLabel_MigrationPaused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running Migration.
        /// </summary>
        public static string StatusLabel_MigrationRunning {
            get {
                return ResourceManager.GetString("StatusLabel_MigrationRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preparing to Run.
        /// </summary>
        public static string StatusLabel_NotRunning {
            get {
                return ResourceManager.GetString("StatusLabel_NotRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paused.
        /// </summary>
        public static string StatusLabel_Paused {
            get {
                return ResourceManager.GetString("StatusLabel_Paused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running.
        /// </summary>
        public static string StatusLabel_Running {
            get {
                return ResourceManager.GetString("StatusLabel_Running", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failures.
        /// </summary>
        public static string StatusSummary_Failures {
            get {
                return ResourceManager.GetString("StatusSummary_Failures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skipped.
        /// </summary>
        public static string StatusSummary_Skipped {
            get {
                return ResourceManager.GetString("StatusSummary_Skipped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successes.
        /// </summary>
        public static string StatusSummary_Successes {
            get {
                return ResourceManager.GetString("StatusSummary_Successes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warnings.
        /// </summary>
        public static string StatusSummary_Warnings {
            get {
                return ResourceManager.GetString("StatusSummary_Warnings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site collection url cannot contain illegal characters.
        /// </summary>
        public static string ValidSiteCollectionURL {
            get {
                return ResourceManager.GetString("ValidSiteCollectionURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site url cannot contain illegal characters.
        /// </summary>
        public static string ValidSiteURL {
            get {
                return ResourceManager.GetString("ValidSiteURL", resourceCulture);
            }
        }
    }
}
