//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Metalogix.MLLicensing.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Metalogix.MLLicensing.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alert!.
        /// </summary>
        public static string Alert_Title {
            get {
                return ResourceManager.GetString("Alert_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please contact sales@metalogix.com to prevent any product usage interruption..
        /// </summary>
        public static string Contact_Sales_For_Limit_About_To_Exceed {
            get {
                return ResourceManager.GetString("Contact_Sales_For_Limit_About_To_Exceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please contact sales@metalogix.com to adjust your license..
        /// </summary>
        public static string Contact_Sales_For_Limit_Exceeded {
            get {
                return ResourceManager.GetString("Contact_Sales_For_Limit_Exceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning: Your license expiration date is in {0} days..
        /// </summary>
        public static string License_About_To_Expire {
            get {
                return ResourceManager.GetString("License_About_To_Expire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License Alert!.
        /// </summary>
        public static string License_Alert_Title {
            get {
                return ResourceManager.GetString("License_Alert_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content Matrix/Organizer License has Expired.
        /// </summary>
        public static string License_Caption {
            get {
                return ResourceManager.GetString("License_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Used: {0} of {1}.
        /// </summary>
        public static string License_Data_Usage {
            get {
                return ResourceManager.GetString("License_Data_Usage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your license has expired. Please contact your Metalogix sales representative or email sales@metalogix.com.
        /// </summary>
        public static string License_Expired {
            get {
                return ResourceManager.GetString("License_Expired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License Expiration: {0}.
        /// </summary>
        public static string License_Expiry_Date {
            get {
                return ResourceManager.GetString("License_Expiry_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your license has expired. The product will stop functioning..
        /// </summary>
        public static string License_Has_Expired {
            get {
                return ResourceManager.GetString("License_Has_Expired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have exceeded the licensed capacity for this license. The product
        ///will stop functioning..
        /// </summary>
        public static string License_Limit_Exceeded {
            get {
                return ResourceManager.GetString("License_Limit_Exceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License Limit Exceeded.
        /// </summary>
        public static string License_Limit_Exceeded_Message {
            get {
                return ResourceManager.GetString("License_Limit_Exceeded_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have exceeded the allowed offline validation period. Please re-activate your license..
        /// </summary>
        public static string License_Offline_Validation_Exceeded {
            get {
                return ResourceManager.GetString("License_Offline_Validation_Exceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning: You are currently at {0}% of the licensed capacity usage of this product..
        /// </summary>
        public static string License_Usage_Warning {
            get {
                return ResourceManager.GetString("License_Usage_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have used more capacity than your current Content Matrix/Organizer license includes. Please contact your Metalogix sales representative or email sales@metalogix.com.
        /// </summary>
        public static string Licensed_Data_Exceeded {
            get {
                return ResourceManager.GetString("Licensed_Data_Exceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning: You are currently at {0}% of the licensed capacity..
        /// </summary>
        public static string LicenseData_Usage_Warning {
            get {
                return ResourceManager.GetString("LicenseData_Usage_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning: Your support &amp;&amp; maintenance expiration date is in {0} days..
        /// </summary>
        public static string Maintenance_About_To_Expire {
            get {
                return ResourceManager.GetString("Maintenance_About_To_Expire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metalogix License.
        /// </summary>
        public static string Metalogix_License {
            get {
                return ResourceManager.GetString("Metalogix_License", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your support &amp;&amp; maintenance has expired. The product will continue to 
        ///function but you will not have access to support or product upgrades..
        /// </summary>
        public static string Support_Maintenance_Expired {
            get {
                return ResourceManager.GetString("Support_Maintenance_Expired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support &amp;&amp; Maintenance Expiration: {0}.
        /// </summary>
        public static string Support_Maintenance_Expiry_Date {
            get {
                return ResourceManager.GetString("Support_Maintenance_Expiry_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suppress this message for {0} days.
        /// </summary>
        public static string Suppress_Alert_Message {
            get {
                return ResourceManager.GetString("Suppress_Alert_Message", resourceCulture);
            }
        }
    }
}
