//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Metalogix.SharePoint.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Metalogix.SharePoint.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to folder.
        /// </summary>
        public static string _Folder {
            get {
                return ResourceManager.GetString("_Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to folders.
        /// </summary>
        public static string _Folders {
            get {
                return ResourceManager.GetString("_Folders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to item.
        /// </summary>
        public static string _Item {
            get {
                return ResourceManager.GetString("_Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to items.
        /// </summary>
        public static string _Items {
            get {
                return ResourceManager.GetString("_Items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to list.
        /// </summary>
        public static string _List {
            get {
                return ResourceManager.GetString("_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lists.
        /// </summary>
        public static string _Lists {
            get {
                return ResourceManager.GetString("_Lists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to site.
        /// </summary>
        public static string _Site {
            get {
                return ResourceManager.GetString("_Site", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to site collection.
        /// </summary>
        public static string _SiteCollection {
            get {
                return ResourceManager.GetString("_SiteCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to site collections.
        /// </summary>
        public static string _SiteCollections {
            get {
                return ResourceManager.GetString("_SiteCollections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sites.
        /// </summary>
        public static string _Sites {
            get {
                return ResourceManager.GetString("_Sites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A dynamically provisioned collection of arbitrary webs is immutable.
        /// </summary>
        public static string AdHoc_Web_Collection_Is_Immutable {
            get {
                return ResourceManager.GetString("AdHoc_Web_Collection_Is_Immutable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Detect.
        /// </summary>
        public static string Auto_Detect {
            get {
                return ResourceManager.GetString("Auto_Detect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bytes Copied.
        /// </summary>
        public static string Bytes_Copied {
            get {
                return ResourceManager.GetString("Bytes_Copied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bytes Restored.
        /// </summary>
        public static string Bytes_Restored {
            get {
                return ResourceManager.GetString("Bytes_Restored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A column with that name already exists..
        /// </summary>
        public static string Column_Name_Already_Exists {
            get {
                return ResourceManager.GetString("Column_Name_Already_Exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Delete.
        /// </summary>
        public static string ConfirmDelete {
            get {
                return ResourceManager.GetString("ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply Content Types to Selected List.
        /// </summary>
        public static string CTypeDialogApplyOption {
            get {
                return ResourceManager.GetString("CTypeDialogApplyOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply Content Types via Rule.
        /// </summary>
        public static string CTypeDialogCreateRule {
            get {
                return ResourceManager.GetString("CTypeDialogCreateRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Options.
        /// </summary>
        public static string CTypeDialogEditOption {
            get {
                return ResourceManager.GetString("CTypeDialogEditOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source List.
        /// </summary>
        public static string CTypeDialogOptionsColumn {
            get {
                return ResourceManager.GetString("CTypeDialogOptionsColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List With Content Types Applied.
        /// </summary>
        public static string CTypeDialogOptionsLabel {
            get {
                return ResourceManager.GetString("CTypeDialogOptionsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applied Content Types.
        /// </summary>
        public static string CTypeDialogOptionsValue {
            get {
                return ResourceManager.GetString("CTypeDialogOptionsValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string CTypeDialogRemoveOption {
            get {
                return ResourceManager.GetString("CTypeDialogRemoveOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply Content Types to Lists.
        /// </summary>
        public static string CTypeDialogTitle {
            get {
                return ResourceManager.GetString("CTypeDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you wish to delete &quot;{0}&quot; permanently?.
        /// </summary>
        public static string DeleteItem {
            get {
                return ResourceManager.GetString("DeleteItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you wish to delete the selected {0} {1} permanently?.
        /// </summary>
        public static string DeleteItems {
            get {
                return ResourceManager.GetString("DeleteItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply Document Set to Selected Folder.
        /// </summary>
        public static string DocSetDialogApplyOption {
            get {
                return ResourceManager.GetString("DocSetDialogApplyOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply Document Set.
        /// </summary>
        public static string DocSetDialogCreateOption {
            get {
                return ResourceManager.GetString("DocSetDialogCreateOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply New Document Sets To Library.
        /// </summary>
        public static string DocSetDialogCreateOptionToList {
            get {
                return ResourceManager.GetString("DocSetDialogCreateOptionToList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply New Document Sets via Rule.
        /// </summary>
        public static string DocSetDialogCreateOptionViaRule {
            get {
                return ResourceManager.GetString("DocSetDialogCreateOptionViaRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Options.
        /// </summary>
        public static string DocSetDialogEditOption {
            get {
                return ResourceManager.GetString("DocSetDialogEditOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder.
        /// </summary>
        public static string DocSetDialogFolderTabObjectColumn {
            get {
                return ResourceManager.GetString("DocSetDialogFolderTabObjectColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Set Content Type.
        /// </summary>
        public static string DocSetDialogFolderTabOptionColumn {
            get {
                return ResourceManager.GetString("DocSetDialogFolderTabOptionColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folders.
        /// </summary>
        public static string DocSetDialogFolderTabTitle {
            get {
                return ResourceManager.GetString("DocSetDialogFolderTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List Filter.
        /// </summary>
        public static string DocSetDialogOptionsColumn {
            get {
                return ResourceManager.GetString("DocSetDialogOptionsColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lists with Document Sets Applied.
        /// </summary>
        public static string DocSetDialogOptionsLabel {
            get {
                return ResourceManager.GetString("DocSetDialogOptionsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applied Document Set Content Types.
        /// </summary>
        public static string DocSetDialogOptionsValue {
            get {
                return ResourceManager.GetString("DocSetDialogOptionsValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lists.
        /// </summary>
        public static string DocSetDialogOriginalTabText {
            get {
                return ResourceManager.GetString("DocSetDialogOriginalTabText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string DocSetDialogRemoveOption {
            get {
                return ResourceManager.GetString("DocSetDialogRemoveOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply Document Sets.
        /// </summary>
        public static string DocSetDialogTitle {
            get {
                return ResourceManager.GetString("DocSetDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string ErrorString {
            get {
                return ResourceManager.GetString("ErrorString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} requires writing directly to the SharePoint database.
        ///In order to enable this, please contact support by going to http://www.metalogix.com/Support#ContactSupport to enable DB writing..
        /// </summary>
        public static string Feature_Requires_DBWriting {
            get {
                return ResourceManager.GetString("Feature_Requires_DBWriting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop! Please ensure that the version of StoragePoint on your Source Farm and the version of StoragePoint on your Target
        ///Farm are identical and running v5.1 or higher. If these are not, you will cause content corruption as a result of this operation..
        /// </summary>
        public static string Feature_StoragePoint_Warning {
            get {
                return ResourceManager.GetString("Feature_StoragePoint_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two or more source folders share the same name. You may want to rename these folders to avoid collisions during the copy..
        /// </summary>
        public static string Folder_Collision_Warning {
            get {
                return ResourceManager.GetString("Folder_Collision_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folders.
        /// </summary>
        public static string FolderPluralizedName {
            get {
                return ResourceManager.GetString("FolderPluralizedName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This copy requires that you rename the site you copied to avoid overwriting your source data. Please ensure that the appropriate rename options have been selected and that you have specified a new name for your target site..
        /// </summary>
        public static string Force_Site_Rename_Warning {
            get {
                return ResourceManager.GetString("Force_Site_Rename_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , corrected={0}.
        /// </summary>
        public static string FS_InfoPathLogEnd {
            get {
                return ResourceManager.GetString("FS_InfoPathLogEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0}] {1}.
        /// </summary>
        public static string FS_InfoPathLogStart {
            get {
                return ResourceManager.GetString("FS_InfoPathLogStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [NOTCHANGED] {0}.
        /// </summary>
        public static string FS_InfoPathRefNotChanged {
            get {
                return ResourceManager.GetString("FS_InfoPathRefNotChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Content Matrix license in use does not allow connections to {0}..
        /// </summary>
        public static string FS_SharePointVersionUnlicensed {
            get {
                return ResourceManager.GetString("FS_SharePointVersionUnlicensed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xml = {0}.
        /// </summary>
        public static string FS_Xml {
            get {
                return ResourceManager.GetString("FS_Xml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified host name is not valid.
        /// </summary>
        public static string Host_Name_Invalid_Warning {
            get {
                return ResourceManager.GetString("Host_Name_Invalid_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not apply host name.
        /// </summary>
        public static string HostName_Change_Failed_Caption {
            get {
                return ResourceManager.GetString("HostName_Change_Failed_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified host name is not valid..
        /// </summary>
        public static string HostName_Change_Failed_Message {
            get {
                return ResourceManager.GetString("HostName_Change_Failed_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The host name associated with this database connection has been set to {0}..
        /// </summary>
        public static string HostName_Change_Successful {
            get {
                return ResourceManager.GetString("HostName_Change_Successful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ---- Attempting to correct reference ----.
        /// </summary>
        public static string InfoPathLogAttemptingToCorrectRefSplitter {
            get {
                return ResourceManager.GetString("InfoPathLogAttemptingToCorrectRefSplitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The authentication method you selected requires Internet Explorer version {0} or later. The Internet Explorer version detected was {1}. Please update Internet Explorer or select a different authentication method..
        /// </summary>
        public static string InsufficientIEMessage {
            get {
                return ResourceManager.GetString("InsufficientIEMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insufficient IE Version.
        /// </summary>
        public static string InsufficientIETitle {
            get {
                return ResourceManager.GetString("InsufficientIETitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Column Name.
        /// </summary>
        public static string Invalid_Column_Name {
            get {
                return ResourceManager.GetString("Invalid_Column_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Options Configuration.
        /// </summary>
        public static string Invalid_Options_Configuration {
            get {
                return ResourceManager.GetString("Invalid_Options_Configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Selection.
        /// </summary>
        public static string Invalid_Selection {
            get {
                return ResourceManager.GetString("Invalid_Selection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two or more source lists share the same name. You may want to rename these lists to avoid collisions during the copy..
        /// </summary>
        public static string List_Collision_Warning {
            get {
                return ResourceManager.GetString("List_Collision_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot Copy: Target Web is the parent of the Source List.
        /// </summary>
        public static string ListCopyOverwriteWarning {
            get {
                return ResourceManager.GetString("ListCopyOverwriteWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lists and Libraries.
        /// </summary>
        public static string ListPluralizedName {
            get {
                return ResourceManager.GetString("ListPluralizedName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Nintex Workflow databases.
        /// </summary>
        public static string Manage_Nintex_Workflow_Databases {
            get {
                return ResourceManager.GetString("Manage_Nintex_Workflow_Databases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual reconnection required..
        /// </summary>
        public static string Manual_Reconnection_Required {
            get {
                return ResourceManager.GetString("Manual_Reconnection_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target content type not found at current scope. This content type is defined at a higher scope in the site collection and cannot be edited..
        /// </summary>
        public static string MsgCannotFindContentType {
            get {
                return ResourceManager.GetString("MsgCannotFindContentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder: &quot;{0}&quot; has been renamed to: &quot;{1}&quot; to satisfy naming requirements of SharePoint 2010. The string &quot;_vti_&quot; cannot be the starting of a folder name in SharePoint 2010..
        /// </summary>
        public static string MsgInvalid2010FolderName {
            get {
                return ResourceManager.GetString("MsgInvalid2010FolderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please ensure that the web application, managed path, or url name of the site collection to be created are different than the source to avoid overwriting source data..
        /// </summary>
        public static string MsgInvalidSiteCollectionSelection {
            get {
                return ResourceManager.GetString("MsgInvalidSiteCollectionSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no web applications that contain valid content databases available..
        /// </summary>
        public static string MsgNoContentDatabasesInWebApps {
            get {
                return ResourceManager.GetString("MsgNoContentDatabasesInWebApps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter an owner for the site collection.
        /// </summary>
        public static string MsgSiteCollectionOwner {
            get {
                return ResourceManager.GetString("MsgSiteCollectionOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a url for the site collection.
        /// </summary>
        public static string MsgSiteCollectionUrl {
            get {
                return ResourceManager.GetString("MsgSiteCollectionUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users not present in active directory must be added directly to the SharePoint Content Database. Writing to the content database is NOT supported by Microsoft. Using this feature is done at your own risk..
        /// </summary>
        public static string MsgUserDbWriteWarning {
            get {
                return ResourceManager.GetString("MsgUserDbWriteWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preserving document IDs.
        /// </summary>
        public static string Preserve_DocumentIDs {
            get {
                return ResourceManager.GetString("Preserve_DocumentIDs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename Selected Node.
        /// </summary>
        public static string RenameDialogApplyOption {
            get {
                return ResourceManager.GetString("RenameDialogApplyOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename Nodes via Rule.
        /// </summary>
        public static string RenameDialogCreateRule {
            get {
                return ResourceManager.GetString("RenameDialogCreateRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Task.
        /// </summary>
        public static string RenameDialogEditOption {
            get {
                return ResourceManager.GetString("RenameDialogEditOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source Node.
        /// </summary>
        public static string RenameDialogOptionsColumn {
            get {
                return ResourceManager.GetString("RenameDialogOptionsColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of Rename Tasks.
        /// </summary>
        public static string RenameDialogOptionsLabel {
            get {
                return ResourceManager.GetString("RenameDialogOptionsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename Operations To Perform.
        /// </summary>
        public static string RenameDialogOptionsValue {
            get {
                return ResourceManager.GetString("RenameDialogOptionsValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Task(s).
        /// </summary>
        public static string RenameDialogRemoveOption {
            get {
                return ResourceManager.GetString("RenameDialogRemoveOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select only one source item when using the &quot;New&quot; button..
        /// </summary>
        public static string Select_One_Source_Item {
            get {
                return ResourceManager.GetString("Select_One_Source_Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shallow copying externalized data.
        /// </summary>
        public static string Shallow_Copying_Externalized_Data {
            get {
                return ResourceManager.GetString("Shallow_Copying_Externalized_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Display Names.
        /// </summary>
        public static string Show_Display_Names {
            get {
                return ResourceManager.GetString("Show_Display_Names", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Internal Names.
        /// </summary>
        public static string Show_Internal_Names {
            get {
                return ResourceManager.GetString("Show_Internal_Names", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two or more source sites share the same name. You may want to rename these sites to avoid collisions during the copy..
        /// </summary>
        public static string Site_Collision_Warning {
            get {
                return ResourceManager.GetString("Site_Collision_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A site column with that name already exists..
        /// </summary>
        public static string Site_Column_Name_Already_Exists {
            get {
                return ResourceManager.GetString("Site_Column_Name_Already_Exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sites.
        /// </summary>
        public static string SitePluralizedName {
            get {
                return ResourceManager.GetString("SitePluralizedName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The action cannot be run as because the source of this operation is currently in use by another action..
        /// </summary>
        public static string SourceInUseError {
            get {
                return ResourceManager.GetString("SourceInUseError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SharePoint 2003.
        /// </summary>
        public static string SP2003 {
            get {
                return ResourceManager.GetString("SP2003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SharePoint 2007.
        /// </summary>
        public static string SP2007 {
            get {
                return ResourceManager.GetString("SP2007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SharePoint 2010.
        /// </summary>
        public static string SP2010 {
            get {
                return ResourceManager.GetString("SP2010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SharePoint 2013.
        /// </summary>
        public static string SP2013 {
            get {
                return ResourceManager.GetString("SP2013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SharePoint 2016.
        /// </summary>
        public static string SP2016 {
            get {
                return ResourceManager.GetString("SP2016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not fetch page layout collection..
        /// </summary>
        public static string SPMasterPageGallery_GetPageLayoutCollection_Could_not_fetch_page_layout_collection_ {
            get {
                return ResourceManager.GetString("SPMasterPageGallery_GetPageLayoutCollection_Could_not_fetch_page_layout_collectio" +
                        "n_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SharePoint Online.
        /// </summary>
        public static string SPOnline {
            get {
                return ResourceManager.GetString("SPOnline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The underlying SharePoint adapter does not support write operations.
        /// </summary>
        public static string TargetIsReadOnly {
            get {
                return ResourceManager.GetString("TargetIsReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not set template location.
        /// </summary>
        public static string Template_Location_Change_Failed_Caption {
            get {
                return ResourceManager.GetString("Template_Location_Change_Failed_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified template location could not be resolved..
        /// </summary>
        public static string Template_Location_Change_Failed_Message {
            get {
                return ResourceManager.GetString("Template_Location_Change_Failed_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The folder used as the template location for this connection has been changed to {0}.
        /// </summary>
        public static string Template_Location_Change_Successful {
            get {
                return ResourceManager.GetString("Template_Location_Change_Successful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changing this setting impacts how data is read from this connection. If there are any actions currently running that use this connection, changing this setting may invalidate their results. Continue?.
        /// </summary>
        public static string Template_Location_Change_Warning {
            get {
                return ResourceManager.GetString("Template_Location_Change_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the folder to be used as the template location. .
        /// </summary>
        public static string Template_Location_Set {
            get {
                return ResourceManager.GetString("Template_Location_Set", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string WarningString {
            get {
                return ResourceManager.GetString("WarningString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workflow Activities with GUID characteristics found in source XOML. Please see details..
        /// </summary>
        public static string Workflow_ActivitiesGuidCharacteristics {
            get {
                return ResourceManager.GetString("Workflow_ActivitiesGuidCharacteristics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analyse source workflow{0}.
        /// </summary>
        public static string Workflow_AnalyseSourceWorkflow {
            get {
                return ResourceManager.GetString("Workflow_AnalyseSourceWorkflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  (Version {0}).
        /// </summary>
        public static string Workflow_AnalyseSourceWorkflowVersion {
            get {
                return ResourceManager.GetString("Workflow_AnalyseSourceWorkflowVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Determine All.
        /// </summary>
        public static string Workflow_DetermineAll {
            get {
                return ResourceManager.GetString("Workflow_DetermineAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem constructing workflow activity namespace dictionary [{0}].Activity &apos;{1}&apos; already has namespace of &apos;{2}&apos; and also appears with namespace &apos;{3}&apos;.
        /// </summary>
        public static string Workflow_ErrorNamespaceDictionary {
            get {
                return ResourceManager.GetString("Workflow_ErrorNamespaceDictionary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initialising Workflow Repository.
        /// </summary>
        public static string Workflow_InitialiseRepository {
            get {
                return ResourceManager.GetString("Workflow_InitialiseRepository", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Initialising the Workflow Repository. Defaulting the repository to utilise the core supported workflow activities within this release build.{0}{1}.
        /// </summary>
        public static string Workflow_InitialiseRepositoryError {
            get {
                return ResourceManager.GetString("Workflow_InitialiseRepositoryError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Total Activities in current configuration. ({1} Core Default Activities).
        /// </summary>
        public static string Workflow_RepositoryActivityInfo {
            get {
                return ResourceManager.GetString("Workflow_RepositoryActivityInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} [{1} Attributes] ({2}).
        /// </summary>
        public static string Workflow_RepositoryVerboseDetail {
            get {
                return ResourceManager.GetString("Workflow_RepositoryVerboseDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supported Workflow Activities:.
        /// </summary>
        public static string Workflow_RepositoryVerboseHeading {
            get {
                return ResourceManager.GetString("Workflow_RepositoryVerboseHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analysis indicates {0} instance(s) where a possible GUID has not been mapped.{1}Details are in the format &apos;ActivityName.AttributeName=GUID&apos; :{2}.
        /// </summary>
        public static string Workflow_UnmappedHeading {
            get {
                return ResourceManager.GetString("Workflow_UnmappedHeading", resourceCulture);
            }
        }
    }
}
