//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Metalogix.Explorer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Metalogix.Explorer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AutoProvisionNewMetabaseFile.
        /// </summary>
        internal static string AutoProvisionNewMetabaseFileKey {
            get {
                return ResourceManager.GetString("AutoProvisionNewMetabaseFileKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified connection string is not present in the current active connections..
        /// </summary>
        internal static string ConnectionStringNotPresent {
            get {
                return ResourceManager.GetString("ConnectionStringNotPresent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FileMetabaseContext.
        /// </summary>
        internal static string FileMetabaseContextKey {
            get {
                return ResourceManager.GetString("FileMetabaseContextKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified target is currently in use as the source of another action and is unavailable for writing..
        /// </summary>
        internal static string SourceInUse {
            get {
                return ResourceManager.GetString("SourceInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQLMetabaseContext.
        /// </summary>
        internal static string SQLMetabaseContextKey {
            get {
                return ResourceManager.GetString("SQLMetabaseContextKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UpgradeActiveConnections.
        /// </summary>
        internal static string UpgradeActiveConnectionsKey {
            get {
                return ResourceManager.GetString("UpgradeActiveConnectionsKey", resourceCulture);
            }
        }
    }
}
