//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Metalogix.SharePoint.Actions.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Metalogix.SharePoint.Actions.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accessing Termstore.
        /// </summary>
        public static string AccessingTermstore {
            get {
                return ResourceManager.GetString("AccessingTermstore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding Taxonomy Group.
        /// </summary>
        public static string AddingTaxonomyGroup {
            get {
                return ResourceManager.GetString("AddingTaxonomyGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding Taxonomy Term.
        /// </summary>
        public static string AddingTaxonomyTerm {
            get {
                return ResourceManager.GetString("AddingTaxonomyTerm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding Taxonomy Termset.
        /// </summary>
        public static string AddingTaxonomyTermset {
            get {
                return ResourceManager.GetString("AddingTaxonomyTermset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applying current theme skipped.
        /// </summary>
        public static string ApplyCurrentTheme {
            get {
                return ResourceManager.GetString("ApplyCurrentTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applying current theme issue.
        /// </summary>
        public static string ApplyTheme {
            get {
                return ResourceManager.GetString("ApplyTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot run action. The target is a child site of the source..
        /// </summary>
        public static string CannotRunTargetIsChildSiteOfSource {
            get {
                return ResourceManager.GetString("CannotRunTargetIsChildSiteOfSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certain managed metadata term guids not found. Please see details..
        /// </summary>
        public static string CertainManagedMetadataTermGuidNotFound {
            get {
                return ResourceManager.GetString("CertainManagedMetadataTermGuidNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broken Links.
        /// </summary>
        public static string CheckLinks_Detail_Failed {
            get {
                return ResourceManager.GetString("CheckLinks_Detail_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flagged Links.
        /// </summary>
        public static string CheckLinks_Detail_Flagged {
            get {
                return ResourceManager.GetString("CheckLinks_Detail_Flagged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working Links.
        /// </summary>
        public static string CheckLinks_Detail_Succeeded {
            get {
                return ResourceManager.GetString("CheckLinks_Detail_Succeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} could not be processed properly for the target. The referenced user does not exist on the target web. This web part will be copied but without a target user..
        /// </summary>
        public static string ContactDetailsWebPartProcessingErrorMessage {
            get {
                return ResourceManager.GetString("ContactDetailsWebPartProcessingErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content Type.
        /// </summary>
        public static string ContentType {
            get {
                return ResourceManager.GetString("ContentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copying Content Type Resource File.
        /// </summary>
        public static string CopyingContentTypeResourceFile {
            get {
                return ResourceManager.GetString("CopyingContentTypeResourceFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copying Content Type Resource Folder For List.
        /// </summary>
        public static string CopyingContentTypeResourceFolderForList {
            get {
                return ResourceManager.GetString("CopyingContentTypeResourceFolderForList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copying masterpage used by source theme to target failed.
        /// </summary>
        public static string CopyMasterpageFailed {
            get {
                return ResourceManager.GetString("CopyMasterpageFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved.
        /// </summary>
        public static string CopyMasterPagesAction_ApprovalStatus_Approved {
            get {
                return ResourceManager.GetString("CopyMasterPagesAction_ApprovalStatus_Approved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draft.
        /// </summary>
        public static string CopyMasterPagesAction_ApprovalStatus_Draft {
            get {
                return ResourceManager.GetString("CopyMasterPagesAction_ApprovalStatus_Draft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending.
        /// </summary>
        public static string CopyMasterPagesAction_ApprovalStatus_Pending {
            get {
                return ResourceManager.GetString("CopyMasterPagesAction_ApprovalStatus_Pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rejected.
        /// </summary>
        public static string CopyMasterPagesAction_ApprovalStatus_Rejected {
            get {
                return ResourceManager.GetString("CopyMasterPagesAction_ApprovalStatus_Rejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scheduled.
        /// </summary>
        public static string CopyMasterPagesAction_ApprovalStatus_Scheduled {
            get {
                return ResourceManager.GetString("CopyMasterPagesAction_ApprovalStatus_Scheduled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding Master Page.
        /// </summary>
        public static string CopyMasterPagesAction_CopyMasterPages_Adding_Master_Page {
            get {
                return ResourceManager.GetString("CopyMasterPagesAction_CopyMasterPages_Adding_Master_Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding Master Page Catalog Items.
        /// </summary>
        public static string CopyMasterPagesAction_CopyMasterPages_Adding_Master_Page_Catalog_Items {
            get {
                return ResourceManager.GetString("CopyMasterPagesAction_CopyMasterPages_Adding_Master_Page_Catalog_Items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding Page Layout.
        /// </summary>
        public static string CopyMasterPagesAction_CopyMasterPages_Adding_Page_Layout {
            get {
                return ResourceManager.GetString("CopyMasterPagesAction_CopyMasterPages_Adding_Page_Layout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot complete this action. File not readable.
        /// </summary>
        public static string CopyMasterPagesAction_CopyMasterPages_Cannot_complete_this_action__File_not_readable {
            get {
                return ResourceManager.GetString("CopyMasterPagesAction_CopyMasterPages_Cannot_complete_this_action__File_not_reada" +
                        "ble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception thrown: &quot;{0}&quot;, please verify that the source page&apos;s moderation status.
        /// </summary>
        public static string CopyMasterPagesAction_CopyMasterPages_Exception_thrown____0____please_verify_that_the_source_page_s_moderation_status {
            get {
                return ResourceManager.GetString("CopyMasterPagesAction_CopyMasterPages_Exception_thrown____0____please_verify_that" +
                        "_the_source_page_s_moderation_status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception thrown: &quot;{0}&quot;, the source page&apos;s moderation status was set as &quot;{1}&quot;, so could not be read..
        /// </summary>
        public static string CopyMasterPagesAction_CopyMasterPages_Exception_thrown____0____the_source_page_s_moderation_status_was_set_as___1____so_could_not_be_read_ {
            get {
                return ResourceManager.GetString("CopyMasterPagesAction_CopyMasterPages_Exception_thrown____0____the_source_page_s_" +
                        "moderation_status_was_set_as___1____so_could_not_be_read_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skipping migration of version {0} (draft hidden) of {1}, as its binaries are inaccessible..
        /// </summary>
        public static string CopyMasterPagesAction_CopyMasterPages_SkipDraftHiddenVersionAsBinariesAreUnavailable {
            get {
                return ResourceManager.GetString("CopyMasterPagesAction_CopyMasterPages_SkipDraftHiddenVersionAsBinariesAreUnavaila" +
                        "ble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source page is ghosted.
        /// </summary>
        public static string CopyMasterPagesAction_CopyMasterPages_Source_page_is_ghosted {
            get {
                return ResourceManager.GetString("CopyMasterPagesAction_CopyMasterPages_Source_page_is_ghosted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copying web parts in document.
        /// </summary>
        public static string CopyWebPartsInDocument {
            get {
                return ResourceManager.GetString("CopyWebPartsInDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data View Web Part.
        /// </summary>
        public static string DataViewWebPart {
            get {
                return ResourceManager.GetString("DataViewWebPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link correction failed for {0}. This web part may not appear correctly on the target. Exception: {1}.
        /// </summary>
        public static string DataViewWebPartProcessingErrorMessage {
            get {
                return ResourceManager.GetString("DataViewWebPartProcessingErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting composed looks on target failed.
        /// </summary>
        public static string DeleteComposedLooksFailed {
            get {
                return ResourceManager.GetString("DeleteComposedLooksFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting current composed look on target failed.
        /// </summary>
        public static string DeleteCurrentLookFailed {
            get {
                return ResourceManager.GetString("DeleteCurrentLookFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting masterpage on target failed.
        /// </summary>
        public static string DeleteMasterpageFailed {
            get {
                return ResourceManager.GetString("DeleteMasterpageFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dependencies.
        /// </summary>
        public static string Dependencies {
            get {
                return ResourceManager.GetString("Dependencies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please ensure the appropriate permissions have been granted..
        /// </summary>
        public static string EnsurePermissionsGranted {
            get {
                return ResourceManager.GetString("EnsurePermissionsGranted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ensuring Taxonomy Term Anchor Existence.
        /// </summary>
        public static string EnsureTaxonomyTermAnchorsExist {
            get {
                return ResourceManager.GetString("EnsureTaxonomyTermAnchorsExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errors have occured. Please review details..
        /// </summary>
        public static string ErrorsHaveOccured {
            get {
                return ResourceManager.GetString("ErrorsHaveOccured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excluding the following field references from being explicitly added:.
        /// </summary>
        public static string ExcludeSpecificFieldRefAddMessage {
            get {
                return ResourceManager.GetString("ExcludeSpecificFieldRefAddMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to copy web parts.
        /// </summary>
        public static string FailedToCopyWebParts {
            get {
                return ResourceManager.GetString("FailedToCopyWebParts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to locate content area on source form page..
        /// </summary>
        public static string FailedToLocateSourceFormContentArea {
            get {
                return ResourceManager.GetString("FailedToLocateSourceFormContentArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to locate content area in target page..
        /// </summary>
        public static string FailedToLocateTargetFormContentArea {
            get {
                return ResourceManager.GetString("FailedToLocateTargetFormContentArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to parse form page web part. .
        /// </summary>
        public static string FailedToParseFormPageWebPart {
            get {
                return ResourceManager.GetString("FailedToParseFormPageWebPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First element must be an object of type SPList..
        /// </summary>
        public static string FirstElementMustBeSPList {
            get {
                return ResourceManager.GetString("FirstElementMustBeSPList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SharePoint version {0} or greater is required..
        /// </summary>
        public static string FS_2013ThemeVersionMessage {
            get {
                return ResourceManager.GetString("FS_2013ThemeVersionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added anchor term &apos;{0}&apos; -&gt; [{1}].
        /// </summary>
        public static string FS_AddedAnchorTerm {
            get {
                return ResourceManager.GetString("FS_AddedAnchorTerm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added via {0} Transformation..
        /// </summary>
        public static string FS_AddedVia {
            get {
                return ResourceManager.GetString("FS_AddedVia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to parent (TermSetItem) is null. [termSet=&apos;{0}&apos;, TargetAnchor=&apos;{1}&apos;].
        /// </summary>
        public static string FS_AnchorParentTermSetItemNull {
            get {
                return ResourceManager.GetString("FS_AnchorParentTermSetItemNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copying InfoPath Template [{0}].
        /// </summary>
        public static string FS_CopyingInfoPathTemplate {
            get {
                return ResourceManager.GetString("FS_CopyingInfoPathTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corrected href from {0} to {1}.
        /// </summary>
        public static string FS_CorrectedInfoPathHREF {
            get {
                return ResourceManager.GetString("FS_CorrectedInfoPathHREF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error synchronising dependency terms.{0}.
        /// </summary>
        public static string FS_ErrorSyncDependencyTerms {
            get {
                return ResourceManager.GetString("FS_ErrorSyncDependencyTerms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field name &apos;{0}&apos; (InternalName &apos;{1}&apos;) already exists on the target. Please review details..
        /// </summary>
        public static string FS_FieldAlreadyExistsOnTarget {
            get {
                return ResourceManager.GetString("FS_FieldAlreadyExistsOnTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue encountered adding anchor term &apos;{0}&apos; to parent TermSetItem &apos;{1}&apos;:.
        /// </summary>
        public static string FS_IssueEncounteredAddingAnchorTerm {
            get {
                return ResourceManager.GetString("FS_IssueEncounteredAddingAnchorTerm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issues encountered during migration.{0}.
        /// </summary>
        public static string FS_IssuesDuringMigration {
            get {
                return ResourceManager.GetString("FS_IssuesDuringMigration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corrected Url &apos;{0}&apos; to &apos;{1}&apos;.
        /// </summary>
        public static string FS_LinkCorrectedFromTo {
            get {
                return ResourceManager.GetString("FS_LinkCorrectedFromTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find lookup list &apos;{0}&apos;. [WebId={1}, ShowField={2}]. Using the original source field lookup ID value as a default. Please ensure the lookup list exists within the appropriate scope of the connection. Possible resolutions include refreshing the parent connection prior to migrating a site or sub sites or connecting to a site that allows this list to be accessed..
        /// </summary>
        public static string FS_LookupListNotFound {
            get {
                return ResourceManager.GetString("FS_LookupListNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field &apos;{0}&apos;:.
        /// </summary>
        public static string FS_ManagedMetadataItemMapFieldLabel {
            get {
                return ResourceManager.GetString("FS_ManagedMetadataItemMapFieldLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value Xml : {0}.
        /// </summary>
        public static string FS_ManagedMetadataItemMapValueXmlLabel {
            get {
                return ResourceManager.GetString("FS_ManagedMetadataItemMapValueXmlLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check the versions of the item being migrated have terms that exist within the source termset.{0}The following managed metadata term guid values could not be found and have been removed during migration:.
        /// </summary>
        public static string FS_ManagedMetadataPleaseCheckVersionsOfItems {
            get {
                return ResourceManager.GetString("FS_ManagedMetadataPleaseCheckVersionsOfItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistics for migration of &apos;{0}&apos; to &apos;{1}&apos;. Please view details..
        /// </summary>
        public static string FS_MigrationStatsInfo {
            get {
                return ResourceManager.GetString("FS_MigrationStatsInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New field name &apos;{0}&apos; (InternalName &apos;{1}&apos;) already exists within the source list. Please review details..
        /// </summary>
        public static string FS_NewFieldAlreadyExistsOnSource {
            get {
                return ResourceManager.GetString("FS_NewFieldAlreadyExistsOnSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.{1}:{2}.
        /// </summary>
        public static string FS_PrefixFieldInfoAndValue {
            get {
                return ResourceManager.GetString("FS_PrefixFieldInfoAndValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please review the results as issues were encountered.{0}.
        /// </summary>
        public static string FS_ReviewResults {
            get {
                return ResourceManager.GetString("FS_ReviewResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transformation of source field type &apos;{0}&apos; into Managed Metadata is currently not supported..
        /// </summary>
        public static string FS_SourceFieldTypeNotSupported {
            get {
                return ResourceManager.GetString("FS_SourceFieldTypeNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronising set {0} of {1}.
        /// </summary>
        public static string FS_SynchronisingSet {
            get {
                return ResourceManager.GetString("FS_SynchronisingSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} not found. Unable to transform field [{1}]..
        /// </summary>
        public static string FS_TermstoreNotFound {
            get {
                return ResourceManager.GetString("FS_TermstoreNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to transform Source field &apos;{0}&apos; (InternalName &apos;{1}&apos;) [Type:{2}] into Target field &apos;{3}&apos; (InternalName &apos;{4}&apos;) [Type:{5}, Termset:{6}.{7}.{8}] as the target field display name or internal name already exists. Please ensure the Display Name and Internal Name for a new field are unique to avoid conflicts and potential issues in converting native SharePoint fields..
        /// </summary>
        public static string FS_UnableToTransformSourceFieldDuplicate {
            get {
                return ResourceManager.GetString("FS_UnableToTransformSourceFieldDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to transform Source field &apos;{0}&apos; (InternalName &apos;{1}&apos;) [Type:{2}] as the field already exists on the target as field &apos;{3}&apos; (InternalName &apos;{4}&apos;) [Type:{5}{6}]. Please create a new field in replacement of this and ensure the Display Name and Internal Name for a new field are unique to avoid conflicts and potential issues..
        /// </summary>
        public static string FS_UnableToTransformTargetFieldTypeMismatch {
            get {
                return ResourceManager.GetString("FS_UnableToTransformTargetFieldTypeMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mapped Guid {0} to {1}.
        /// </summary>
        public static string FS_VerboseGuidMapFromTo {
            get {
                return ResourceManager.GetString("FS_VerboseGuidMapFromTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added new field &apos;{0}&apos; (InternalName &apos;{1}&apos;)&apos; in relation to site column &apos;{2}&apos; transformation..
        /// </summary>
        public static string FS_VerboseNewFieldAddedToContentType {
            get {
                return ResourceManager.GetString("FS_VerboseNewFieldAddedToContentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source field &apos;{0}&apos; [Type:{1}] transformed into Target field &apos;{2}&apos; [Type:{3}, Termset:{4}.{5}.{6}].
        /// </summary>
        public static string FS_VerboseSourceFieldTransformation {
            get {
                return ResourceManager.GetString("FS_VerboseSourceFieldTransformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source field &apos;{0}&apos; [value:{1}] transformed to Target field &apos;{2}&apos; [value:{3}].
        /// </summary>
        public static string FS_VerboseSourceItemTransformation {
            get {
                return ResourceManager.GetString("FS_VerboseSourceItemTransformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warnings have occured.{0}Please review details..
        /// </summary>
        public static string FS_WarningsHaveOccured {
            get {
                return ResourceManager.GetString("FS_WarningsHaveOccured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please review details..
        /// </summary>
        public static string GenericExceptionMessage {
            get {
                return ResourceManager.GetString("GenericExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} could not be processed properly for the target. The web part may still be copied but there may be issues with it such as references not being link corrected. The error message is: {1}.
        /// </summary>
        public static string GenericWebPartProcessingErrorMessage {
            get {
                return ResourceManager.GetString("GenericWebPartProcessingErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Migration of InfoPath form template is not supported on target..
        /// </summary>
        public static string InfoPathMigrationNotSupported {
            get {
                return ResourceManager.GetString("InfoPathMigrationNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Library.
        /// </summary>
        public static string Library {
            get {
                return ResourceManager.GetString("Library", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List.
        /// </summary>
        public static string List {
            get {
                return ResourceManager.GetString("List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Term guid(s): .
        /// </summary>
        public static string ManagedMetadataItemMapTermGuidLabel {
            get {
                return ResourceManager.GetString("ManagedMetadataItemMapTermGuidLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mapping List Template.
        /// </summary>
        public static string MappingListTemplate {
            get {
                return ResourceManager.GetString("MappingListTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mapping List Template [{0} to {1}].
        /// </summary>
        public static string MappingListTemplateExceptionMessage {
            get {
                return ResourceManager.GetString("MappingListTemplateExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mapped template &apos;{0}&apos; to &apos;{1}&apos; as &apos;{0}&apos; does not exist on the target..
        /// </summary>
        public static string MappingListTemplateInfoMessage {
            get {
                return ResourceManager.GetString("MappingListTemplateInfoMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master page copying is not supported in the downgrade case..
        /// </summary>
        public static string MasterPageDownGradeError {
            get {
                return ResourceManager.GetString("MasterPageDownGradeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} could not be processed properly for the target. A Site Users web part could not copied correctly. The referenced group does not exist on the target web. The web part will display people and groups with direct permissions on this site..
        /// </summary>
        public static string MembersWebPartProcessingErrorMessage {
            get {
                return ResourceManager.GetString("MembersWebPartProcessingErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resolving and migrating required managed metadata.
        /// </summary>
        public static string MigratingAndResolvingRequiredManagedMetadata {
            get {
                return ResourceManager.GetString("MigratingAndResolvingRequiredManagedMetadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Migrating Local Site Collection Managed Metadata.
        /// </summary>
        public static string MigratingLocalSiteCollectionManagedMetadata {
            get {
                return ResourceManager.GetString("MigratingLocalSiteCollectionManagedMetadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Migrating Server Taxonomies.
        /// </summary>
        public static string MigratingServerTaxonomies {
            get {
                return ResourceManager.GetString("MigratingServerTaxonomies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Migrating Term Store.
        /// </summary>
        public static string MigratingTermStore {
            get {
                return ResourceManager.GetString("MigratingTermStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folders Copied.
        /// </summary>
        public static string Migration_Detail_FoldersCopied {
            get {
                return ResourceManager.GetString("Migration_Detail_FoldersCopied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Groups Copied.
        /// </summary>
        public static string Migration_Detail_GroupsCopied {
            get {
                return ResourceManager.GetString("Migration_Detail_GroupsCopied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items Copied.
        /// </summary>
        public static string Migration_Detail_ItemsCopied {
            get {
                return ResourceManager.GetString("Migration_Detail_ItemsCopied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lists Copied.
        /// </summary>
        public static string Migration_Detail_ListsCopied {
            get {
                return ResourceManager.GetString("Migration_Detail_ListsCopied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role Assignments Copied.
        /// </summary>
        public static string Migration_Detail_RoleAssignments {
            get {
                return ResourceManager.GetString("Migration_Detail_RoleAssignments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sites Copied.
        /// </summary>
        public static string Migration_Detail_SitesCopied {
            get {
                return ResourceManager.GetString("Migration_Detail_SitesCopied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users Copied.
        /// </summary>
        public static string Migration_Detail_UsersCopied {
            get {
                return ResourceManager.GetString("Migration_Detail_UsersCopied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 15.0.4420.1017.
        /// </summary>
        public static string MinimumSharePointVersionFor2013Theme {
            get {
                return ResourceManager.GetString("MinimumSharePointVersionFor2013Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nintex workflows will not be able to migrate to SharePoint Online without the presence of &quot;Nintex&quot; license or the SharePoint Add-In &quot;Nintex Workflows for Office 365&quot; present at the target. Please validate the the same are present prior to migration should Nintex workflow migration be desired..
        /// </summary>
        public static string NintexWorkflowAppWarning {
            get {
                return ResourceManager.GetString("NintexWorkflowAppWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master pages do not exist in SharePoint 2003..
        /// </summary>
        public static string No2003MasterPagesError {
            get {
                return ResourceManager.GetString("No2003MasterPagesError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No place holder master page data stored for target SharePoint version..
        /// </summary>
        public static string NoPlaceHoderMasterPageDataForVersionError {
            get {
                return ResourceManager.GetString("NoPlaceHoderMasterPageDataForVersionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No term stores exist on the source..
        /// </summary>
        public static string NoSourceTermstores {
            get {
                return ResourceManager.GetString("NoSourceTermstores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No term stores exist on the target..
        /// </summary>
        public static string NoTargetTermstores {
            get {
                return ResourceManager.GetString("NoTargetTermstores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The target SharePoint version does not support any of the source page&apos;s UI versions..
        /// </summary>
        public static string NotSupportedUIVersionError {
            get {
                return ResourceManager.GetString("NotSupportedUIVersionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obtaining Lookup Value.
        /// </summary>
        public static string ObtainingLookupValue {
            get {
                return ResourceManager.GetString("ObtainingLookupValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partially successful, please review details..
        /// </summary>
        public static string PartialSuccessReviewDetails {
            get {
                return ResourceManager.GetString("PartialSuccessReviewDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please review the individual related log items for further details..
        /// </summary>
        public static string PleaseReviewTheRelatedLogItemsForDetails {
            get {
                return ResourceManager.GetString("PleaseReviewTheRelatedLogItemsForDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing Data View Web Part.
        /// </summary>
        public static string ProcessingDataViewWebPart {
            get {
                return ResourceManager.GetString("ProcessingDataViewWebPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing Web Parts.
        /// </summary>
        public static string ProcessingWebParts {
            get {
                return ResourceManager.GetString("ProcessingWebParts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The target page layout name could not be set as its URL was not in the valid format : {0}.
        /// </summary>
        public static string PublishingDataUpdater_ParsePageLayoutName_The_target_page_layout_name_could_not_be_set_as_its_URL_was_not_in_the_valid_format {
            get {
                return ResourceManager.GetString("PublishingDataUpdater_ParsePageLayoutName_The_target_page_layout_name_could_not_b" +
                        "e_set_as_its_URL_was_not_in_the_valid_format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The page layout &apos;{0}&apos; cannot be found in the target web&apos;s masterpage gallery, and there are no other page layouts on the target using content type &apos;{1}&apos;. Please check the target library, then try again..
        /// </summary>
        public static string PublishingDataUpdater_SetAppropriateLayoutFromTargetPageLayouts_PageLayoutNullException {
            get {
                return ResourceManager.GetString("PublishingDataUpdater_SetAppropriateLayoutFromTargetPageLayouts_PageLayoutNullExc" +
                        "eption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The page layout &apos;EnterpriseWiki.aspx (Basic Page)&apos; cannot be found in the target web&apos;s masterpage gallery. Please check, then try again..
        /// </summary>
        public static string PublishingDataUpdater_SetEnterprisePageLayoutFromTarget_The_pagelayout__EnterpriseWikiaspx_could_not_be_found {
            get {
                return ResourceManager.GetString("PublishingDataUpdater_SetEnterprisePageLayoutFromTarget_The_pagelayout__Enterpris" +
                        "eWikiaspx_could_not_be_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refreshing Term Stores.
        /// </summary>
        public static string RefreshingTermstores {
            get {
                return ResourceManager.GetString("RefreshingTermstores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run operation call does not incude the required number of parameters..
        /// </summary>
        public static string RunOperationWrongParameterNumber {
            get {
                return ResourceManager.GetString("RunOperationWrongParameterNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second element must be an object of type SPList.
        /// </summary>
        public static string SecondElementMustBeSPList {
            get {
                return ResourceManager.GetString("SecondElementMustBeSPList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This operation is not supported at present on single managed metadata service configurations..
        /// </summary>
        public static string SingleMMDServiceNotSupportedYet {
            get {
                return ResourceManager.GetString("SingleMMDServiceNotSupportedYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site.
        /// </summary>
        public static string Site {
            get {
                return ResourceManager.GetString("Site", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site Column.
        /// </summary>
        public static string SiteColumn {
            get {
                return ResourceManager.GetString("SiteColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source term stores refreshed.
        /// </summary>
        public static string SourceTermstoresRefreshed {
            get {
                return ResourceManager.GetString("SourceTermstoresRefreshed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restoration Aborted.
        /// </summary>
        public static string StatusLabel_RestorationAborted {
            get {
                return ResourceManager.GetString("StatusLabel_RestorationAborted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restoration Completed.
        /// </summary>
        public static string StatusLabel_RestorationComplete {
            get {
                return ResourceManager.GetString("StatusLabel_RestorationComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restoration Failed.
        /// </summary>
        public static string StatusLabel_RestorationFailed {
            get {
                return ResourceManager.GetString("StatusLabel_RestorationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preparing to Run Restoration.
        /// </summary>
        public static string StatusLabel_RestorationNotRunning {
            get {
                return ResourceManager.GetString("StatusLabel_RestorationNotRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restoration Paused.
        /// </summary>
        public static string StatusLabel_RestorationPaused {
            get {
                return ResourceManager.GetString("StatusLabel_RestorationPaused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running Restoration.
        /// </summary>
        public static string StatusLabel_RestorationRunning {
            get {
                return ResourceManager.GetString("StatusLabel_RestorationRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restoration Completed With Warnings.
        /// </summary>
        public static string StatusLabel_RestorationWarning {
            get {
                return ResourceManager.GetString("StatusLabel_RestorationWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success, please review details..
        /// </summary>
        public static string SuccessReviewDetails {
            get {
                return ResourceManager.GetString("SuccessReviewDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target must be SharePoint 2010 or later..
        /// </summary>
        public static string TargetMustBeSharePoint2010 {
            get {
                return ResourceManager.GetString("TargetMustBeSharePoint2010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target term stores refreshed.
        /// </summary>
        public static string TargetTermstoresRefreshed {
            get {
                return ResourceManager.GetString("TargetTermstoresRefreshed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taxonomy.
        /// </summary>
        public static string Taxonomy {
            get {
                return ResourceManager.GetString("Taxonomy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , taxonomy binding is different : SspId=&apos;{0}&apos;, TermSetId=&apos;{1}&apos;.
        /// </summary>
        public static string TaxonomyBindingInfoDifferent {
            get {
                return ResourceManager.GetString("TaxonomyBindingInfoDifferent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , determined taxonomy type mismatch [Type &apos;{0}&apos;].
        /// </summary>
        public static string TaxonomyTypeMismatch {
            get {
                return ResourceManager.GetString("TaxonomyTypeMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms with the same name (or label) and a different guid already exist within the term set or parent term. When migrating a term store please ensure no same named terms (or labels) exist in the termset or parent term..
        /// </summary>
        public static string TermsExistWithDifferentGuid {
            get {
                return ResourceManager.GetString("TermsExistWithDifferentGuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Migration Statistics.
        /// </summary>
        public static string TermStoreStats {
            get {
                return ResourceManager.GetString("TermStoreStats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transform.
        /// </summary>
        public static string Transform {
            get {
                return ResourceManager.GetString("Transform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to determine the default source site collection term store. Please see details..
        /// </summary>
        public static string UnableToDetemineDefaultSourceSiteCollectionTermstore {
            get {
                return ResourceManager.GetString("UnableToDetemineDefaultSourceSiteCollectionTermstore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to determine the default target site collection term store. Please see details..
        /// </summary>
        public static string UnableToDetemineDefaultTargetSiteCollectionTermstore {
            get {
                return ResourceManager.GetString("UnableToDetemineDefaultTargetSiteCollectionTermstore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please ensure that a managed metadata service connection has been designated to be the default site collection term store. This can be done using SharePoint Central Administration-&gt;Manage Service Connections-&gt;[your managed metadata service connection]-&gt;Properties-&gt;set option: &apos;This service application is the default storage location for column specific term sets.&apos;
        ///
        ///Please also ensure the required permissions to access the managed metadata service and term store are present for the migrating user.
        ///.
        /// </summary>
        public static string UnableToDetermineSiteCollectionTermstoreDetails {
            get {
                return ResourceManager.GetString("UnableToDetermineSiteCollectionTermstoreDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to determine the source local site collection group..
        /// </summary>
        public static string UnableToDetermineSourceLocalGroup {
            get {
                return ResourceManager.GetString("UnableToDetermineSourceLocalGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to obtain taxonomy binding information..
        /// </summary>
        public static string UnableToObtainTaxonomyBindingInfo {
            get {
                return ResourceManager.GetString("UnableToObtainTaxonomyBindingInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verbose Logging Enabled.
        /// </summary>
        public static string VerboseLoggingEnabled {
            get {
                return ResourceManager.GetString("VerboseLoggingEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configured target web application &quot;{0}&quot; was not found..
        /// </summary>
        public static string WebAppNotFoundMessage {
            get {
                return ResourceManager.GetString("WebAppNotFoundMessage", resourceCulture);
            }
        }
    }
}
