//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Metalogix.SharePoint.Adapters.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Metalogix.SharePoint.Adapters.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding SharePoint 2013 Workflow Association.
        /// </summary>
        public static string AddSP2013WorkflowLogItem {
            get {
                return ResourceManager.GetString("AddSP2013WorkflowLogItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot parse area between tags. No closing tag detected..
        /// </summary>
        public static string CannotParseTagAreaNoClosingTag {
            get {
                return ResourceManager.GetString("CannotParseTagAreaNoClosingTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot parse area between tags. Start tag is not an opening tag..
        /// </summary>
        public static string CannotParseTagAreaStartTagNotOpening {
            get {
                return ResourceManager.GetString("CannotParseTagAreaStartTagNotOpening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to commandName cannot be null or empty.
        /// </summary>
        public static string CommandNameIsNull {
            get {
                return ResourceManager.GetString("CommandNameIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command &apos;{0}&apos; has not been implemented within &apos;{1}&apos; adapter.
        /// </summary>
        public static string CommandNotImplemented {
            get {
                return ResourceManager.GetString("CommandNotImplemented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to retrieve SharePoint Online cookies. CSOM client unavailable..
        /// </summary>
        public static string CSOM_Client_Unavailable {
            get {
                return ResourceManager.GetString("CSOM_Client_Unavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in executing command &apos;{0}&apos; in &apos;{1}&apos; adapter.
        /// </summary>
        public static string ErrorInCommandExecution {
            get {
                return ResourceManager.GetString("ErrorInCommandExecution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0}].
        /// </summary>
        public static string FS_Brackets {
            get {
                return ResourceManager.GetString("FS_Brackets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not shallow copy data: {0}.
        /// </summary>
        public static string FS_ShallowCopyingInvalid {
            get {
                return ResourceManager.GetString("FS_ShallowCopyingInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Migrating user &apos;{0}&apos; requires explicit Full Control on the web application where the site collection is intented to be created.If the migrating user is a member of the Farm Administrators group then connect to the Central Administration site and try again..
        /// </summary>
        public static string FS_UnableToCreateSC {
            get {
                return ResourceManager.GetString("FS_UnableToCreateSC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The content type workflow association failed to migrate with exception: {0}.
        /// </summary>
        public static string FS_UnableToMigrateContentTypeWorkflow {
            get {
                return ResourceManager.GetString("FS_UnableToMigrateContentTypeWorkflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to obtain Web Application &apos;{0}&apos;.
        /// </summary>
        public static string FS_UnableToObtainWebApplication {
            get {
                return ResourceManager.GetString("FS_UnableToObtainWebApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This adapter reports item permission uniqueness in its returned item XML. It should never be necessary to call this method..
        /// </summary>
        public static string HasUniquePermissionsNotNecessary {
            get {
                return ResourceManager.GetString("HasUniquePermissionsNotNecessary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The version of Internet Explorer detected is insufficient to perform this operation. Internet Explorer version {0} was detected when version {1} or later was required.
        /// </summary>
        public static string InsufficientIEVersionMessage {
            get {
                return ResourceManager.GetString("InsufficientIEVersionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid command name &apos;{0}&apos;.
        /// </summary>
        public static string InvalidCommandName {
            get {
                return ResourceManager.GetString("InvalidCommandName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This method has not been implemented on this adapter type..
        /// </summary>
        public static string Method_Not_Implemented {
            get {
                return ResourceManager.GetString("Method_Not_Implemented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected content database does not exist in the object model. The new site collection cannot be added to it..
        /// </summary>
        public static string MsgCannotFindContentDatabase {
            get {
                return ResourceManager.GetString("MsgCannotFindContentDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target content type not found at current scope. This content type is defined at a higher scope in the site collection and cannot be edited..
        /// </summary>
        public static string MsgCannotFindContentType {
            get {
                return ResourceManager.GetString("MsgCannotFindContentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The templates for the given source language ({0}) cannot be found on the target server. This is most likely due to the source language pack not being installed on the target server..
        /// </summary>
        public static string MsgCannotFindLanguageTemplates {
            get {
                return ResourceManager.GetString("MsgCannotFindLanguageTemplates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This template does not exist on the target server. Please install this template on the target machine or map it to an existing template..
        /// </summary>
        public static string MsgWebTemplateMissing {
            get {
                return ResourceManager.GetString("MsgWebTemplateMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No connections attempted..
        /// </summary>
        public static string No_Connections_Attempted {
            get {
                return ResourceManager.GetString("No_Connections_Attempted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is not a valid absolute URL..
        /// </summary>
        public static string Not_A_Valid_Absolute_URL {
            get {
                return ResourceManager.GetString("Not_A_Valid_Absolute_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL Server Database is not a SharePoint Database..
        /// </summary>
        public static string NotSharePointDatabase {
            get {
                return ResourceManager.GetString("NotSharePointDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This operation is not supported by the underlying adapter{0}Operation: {1}{0}Adapter Type: {2}{0}.
        /// </summary>
        public static string NotSupportedByAdapter {
            get {
                return ResourceManager.GetString("NotSupportedByAdapter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please review details..
        /// </summary>
        public static string PleaseReviewDetails {
            get {
                return ResourceManager.GetString("PleaseReviewDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred during the operation of a service method: {0}.
        /// </summary>
        public static string ServiceError {
            get {
                return ResourceManager.GetString("ServiceError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not instantiate a service required for native remote communication with SharePoint 2013. This may be because .Net 4.0 is not installed in this environment..
        /// </summary>
        public static string ServiceNotFound {
            get {
                return ResourceManager.GetString("ServiceNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connections to SharePoint 2013 or SharePoint 2016 are not available using Migration Manager for SharePoint license keys. Please upgrade to a full Content Matrix license to use these features..
        /// </summary>
        public static string SharePoint_Not_Supported_By_License {
            get {
                return ResourceManager.GetString("SharePoint_Not_Supported_By_License", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SharePoint 2007 Workflows feature is not activated on the target..
        /// </summary>
        public static string SharePoint2007WorkflowFeatureNotActivated {
            get {
                return ResourceManager.GetString("SharePoint2007WorkflowFeatureNotActivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SharePoint 2013 Workflows feature is not activated on the target.
        /// </summary>
        public static string SharePoint2013WorkflowFeatureNotActivated {
            get {
                return ResourceManager.GetString("SharePoint2013WorkflowFeatureNotActivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specified start index is outside the bounds of the given string..
        /// </summary>
        public static string StartIndexOutsideTheBoundsOfString {
            get {
                return ResourceManager.GetString("StartIndexOutsideTheBoundsOfString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provided content is not a StoragePoint blob reference.
        /// </summary>
        public static string StoragePointCannotValidateBlobRef {
            get {
                return ResourceManager.GetString("StoragePointCannotValidateBlobRef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StoragePoint is not configured for the target environment.
        /// </summary>
        public static string StoragePointNotConfigured {
            get {
                return ResourceManager.GetString("StoragePointNotConfigured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A problem was encountered in connecting to the database..
        /// </summary>
        public static string UnableToConnectToDatabase {
            get {
                return ResourceManager.GetString("UnableToConnectToDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to create a site collection using Self Service Site Creation under the Administration Web Application.
        /// </summary>
        public static string UnableToCreateSCUnderCentralAdmin {
            get {
                return ResourceManager.GetString("UnableToCreateSCUnderCentralAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to adapterResultXml is empty or null. Unable to determine the result of the adapter operation..
        /// </summary>
        public static string UnableToDetermineAdapterResult {
            get {
                return ResourceManager.GetString("UnableToDetermineAdapterResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find the workflow association in the list after addition..
        /// </summary>
        public static string UnableToFindWorkflowAssociationInList {
            get {
                return ResourceManager.GetString("UnableToFindWorkflowAssociationInList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AddWebWorkflowAssociation() - Unable to find the workflow association within the web after addition..
        /// </summary>
        public static string UnableToFindWorkflowAssociationInWeb {
            get {
                return ResourceManager.GetString("UnableToFindWorkflowAssociationInWeb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The OOB list workflow association cannot be migrated. The workflow template could not be retrieved from the server. Please ensure &apos;SharePoint 2007 Workflows&apos; feature is activated on the target site collection..
        /// </summary>
        public static string UnableToMigrateListWorkflowAssociation {
            get {
                return ResourceManager.GetString("UnableToMigrateListWorkflowAssociation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A problem was encountered in obtaining workflow instances..
        /// </summary>
        public static string UnableToObtainWorkflowInstances {
            get {
                return ResourceManager.GetString("UnableToObtainWorkflowInstances", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to parse text value. The specified value is empty..
        /// </summary>
        public static string UnableToParseTextValueIsEmpty {
            get {
                return ResourceManager.GetString("UnableToParseTextValueIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The database adapter type was not able to be resolved or loaded..
        /// </summary>
        public static string UnableToResolveDBAdapterType {
            get {
                return ResourceManager.GetString("UnableToResolveDBAdapterType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The assembly required for this type may not be present in the GAC..
        /// </summary>
        public static string UnableToResolveDBAdapterTypeDetails {
            get {
                return ResourceManager.GetString("UnableToResolveDBAdapterTypeDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The workflow template for workflow: {0} could not be retrieved from the server. Please ensure the hidden Workflows list copied correctly..
        /// </summary>
        public static string UnableToRetrieveSPDWorkflow {
            get {
                return ResourceManager.GetString("UnableToRetrieveSPDWorkflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to retrieve the workflow template from the server. Please ensure all necessary features are activated..
        /// </summary>
        public static string UnableToRetrieveWorkflowTemplate {
            get {
                return ResourceManager.GetString("UnableToRetrieveWorkflowTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please ensure all necessary features are activated..
        /// </summary>
        public static string UnableToRetrieveWorkflowTemplateReplace {
            get {
                return ResourceManager.GetString("UnableToRetrieveWorkflowTemplateReplace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is already a workflow association with this name.
        /// </summary>
        public static string UnableToUpdateAlreadyExistsSharePointError {
            get {
                return ResourceManager.GetString("UnableToUpdateAlreadyExistsSharePointError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected end of aspx content reached..
        /// </summary>
        public static string UnexpectedEndOfAspxContent {
            get {
                return ResourceManager.GetString("UnexpectedEndOfAspxContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected end of text reached. Failed to locate tag closing bracket..
        /// </summary>
        public static string UnexpectedEndOfTextFailedToLocateClosingBracket {
            get {
                return ResourceManager.GetString("UnexpectedEndOfTextFailedToLocateClosingBracket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected end of text reached. The last tag is incomplete..
        /// </summary>
        public static string UnexpectedEndOfTextLastTagIncomplete {
            get {
                return ResourceManager.GetString("UnexpectedEndOfTextLastTagIncomplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected end of text reached. Not all tags were closed..
        /// </summary>
        public static string UnexpectedEndOfTextNotAllTagsClosed {
            get {
                return ResourceManager.GetString("UnexpectedEndOfTextNotAllTagsClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The maximum number of tries for correcting the site url have been reached. (max iterations: {0}, site url: {1}).
        /// </summary>
        public static string UrlUtils_GetValidSiteUrl_MaxTriesReached {
            get {
                return ResourceManager.GetString("UrlUtils_GetValidSiteUrl_MaxTriesReached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating new history list with name {0}.
        /// </summary>
        public static string WorkflowHistoryListCreation {
            get {
                return ResourceManager.GetString("WorkflowHistoryListCreation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find a suitable history list on the target to apply the workflow association to..
        /// </summary>
        public static string WorkflowHistoryListNotFound {
            get {
                return ResourceManager.GetString("WorkflowHistoryListNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workflow instances not supported in CSOM.
        /// </summary>
        public static string WorkflowInstanceNotSupportedInCSOM {
            get {
                return ResourceManager.GetString("WorkflowInstanceNotSupportedInCSOM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workflow Instances.
        /// </summary>
        public static string WorkflowInstances {
            get {
                return ResourceManager.GetString("WorkflowInstances", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The workflow association scope attribute is invalid, cannot add a new workflow association.
        /// </summary>
        public static string WorkflowScopeInvalid {
            get {
                return ResourceManager.GetString("WorkflowScopeInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The workflow association scope attribute was null, cannot add a new workflow association.
        /// </summary>
        public static string WorkflowScopeNotFound {
            get {
                return ResourceManager.GetString("WorkflowScopeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find a suitable list on the target to apply the workflow association to..
        /// </summary>
        public static string WorkflowTargetListNotFound {
            get {
                return ResourceManager.GetString("WorkflowTargetListNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating new task list with name {0}.
        /// </summary>
        public static string WorkflowTaskListCreation {
            get {
                return ResourceManager.GetString("WorkflowTaskListCreation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find a suitable tasks list on the target to apply the workflow association to..
        /// </summary>
        public static string WorkflowTaskListNotFound {
            get {
                return ResourceManager.GetString("WorkflowTaskListNotFound", resourceCulture);
            }
        }
    }
}
