//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Metalogix.Client.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Metalogix.Client.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AutoUpdateSettings.
        /// </summary>
        public static string AutoUpdateSettingsKey {
            get {
                return ResourceManager.GetString("AutoUpdateSettingsKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AutoUpdateSkipVersion.
        /// </summary>
        public static string AutoUpdateSkipVersionKey {
            get {
                return ResourceManager.GetString("AutoUpdateSkipVersionKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DefaultMetabaseAdapter.
        /// </summary>
        public static string DefaultMetabaseAdapterKey {
            get {
                return ResourceManager.GetString("DefaultMetabaseAdapterKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Dn {
            get {
                object obj = ResourceManager.GetObject("Dn", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public Folder Edition.
        /// </summary>
        public static string Lic_565 {
            get {
                return ResourceManager.GetString("Lic_565", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SharePoint Edition.
        /// </summary>
        public static string Lic_572 {
            get {
                return ResourceManager.GetString("Lic_572", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Share Edition.
        /// </summary>
        public static string Lic_573 {
            get {
                return ResourceManager.GetString("Lic_573", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website Edition.
        /// </summary>
        public static string Lic_574 {
            get {
                return ResourceManager.GetString("Lic_574", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eRoom Edition.
        /// </summary>
        public static string Lic_575 {
            get {
                return ResourceManager.GetString("Lic_575", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oracle Content Server &amp; Stellent Edition.
        /// </summary>
        public static string Lic_576 {
            get {
                return ResourceManager.GetString("Lic_576", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MCMS 2002 Edition.
        /// </summary>
        public static string Lic_577 {
            get {
                return ResourceManager.GetString("Lic_577", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blogs and Wikis Edition.
        /// </summary>
        public static string Lic_578 {
            get {
                return ResourceManager.GetString("Lic_578", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Google Edition.
        /// </summary>
        public static string Lic_579 {
            get {
                return ResourceManager.GetString("Lic_579", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dedicated Cloud Edition.
        /// </summary>
        public static string Lic_584 {
            get {
                return ResourceManager.GetString("Lic_584", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metalogix Selective Restore Manager for SharePoint.
        /// </summary>
        public static string Lic_585 {
            get {
                return ResourceManager.GetString("Lic_585", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Share Edition V3.
        /// </summary>
        public static string Lic_586 {
            get {
                return ResourceManager.GetString("Lic_586", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Migration Manager for SharePoint V3.
        /// </summary>
        public static string Lic_587 {
            get {
                return ResourceManager.GetString("Lic_587", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website V3 Edition.
        /// </summary>
        public static string Lic_588 {
            get {
                return ResourceManager.GetString("Lic_588", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LiveLink Edition.
        /// </summary>
        public static string Lic_589 {
            get {
                return ResourceManager.GetString("Lic_589", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documentum Edition.
        /// </summary>
        public static string Lic_593 {
            get {
                return ResourceManager.GetString("Lic_593", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content Manager.
        /// </summary>
        public static string Lic_722 {
            get {
                return ResourceManager.GetString("Lic_722", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Edition.
        /// </summary>
        public static string Lic_Edition {
            get {
                return ResourceManager.GetString("Lic_Edition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard.
        /// </summary>
        public static string Lic_Edition_0 {
            get {
                return ResourceManager.GetString("Lic_Edition_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StoragePoint.
        /// </summary>
        public static string Lic_Edition_1 {
            get {
                return ResourceManager.GetString("Lic_Edition_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Licensed Editions in this Suite:.
        /// </summary>
        public static string License_Allowed_Editions {
            get {
                return ResourceManager.GetString("License_Allowed_Editions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your current license does not support this feature.
        /// </summary>
        public static string License_Feature_Not_Supported {
            get {
                return ResourceManager.GetString("License_Feature_Not_Supported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Up {
            get {
                object obj = ResourceManager.GetObject("Up", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
