//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Metalogix.SharePoint.Options.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Metalogix.SharePoint.Options.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field Filter.
        /// </summary>
        internal static string FMMOFieldFilter {
            get {
                return ResourceManager.GetString("FMMOFieldFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value Filter.
        /// </summary>
        internal static string FMMOItemFieldValueFilter {
            get {
                return ResourceManager.GetString("FMMOItemFieldValueFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List Filter.
        /// </summary>
        internal static string FMMOListFilter {
            get {
                return ResourceManager.GetString("FMMOListFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Field.
        /// </summary>
        internal static string FMMONewField {
            get {
                return ResourceManager.GetString("FMMONewField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string FMMONo {
            get {
                return ResourceManager.GetString("FMMONo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field Value Substitutes.
        /// </summary>
        internal static string FMMONoOfSubstitutes {
            get {
                return ResourceManager.GetString("FMMONoOfSubstitutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Substitute.
        /// </summary>
        internal static string FMMOSubstitutionValue {
            get {
                return ResourceManager.GetString("FMMOSubstitutionValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string FMMOYes {
            get {
                return ResourceManager.GetString("FMMOYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site Column Filter.
        /// </summary>
        internal static string SCMMOSiteColumnFilter {
            get {
                return ResourceManager.GetString("SCMMOSiteColumnFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site Filter.
        /// </summary>
        internal static string SCMMOSiteFilter {
            get {
                return ResourceManager.GetString("SCMMOSiteFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anchor.
        /// </summary>
        internal static string TargetAnchor {
            get {
                return ResourceManager.GetString("TargetAnchor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Term Group.
        /// </summary>
        internal static string TargetTermGroup {
            get {
                return ResourceManager.GetString("TargetTermGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Term Set.
        /// </summary>
        internal static string TargetTermSet {
            get {
                return ResourceManager.GetString("TargetTermSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target Termstore.
        /// </summary>
        internal static string TargetTermstore {
            get {
                return ResourceManager.GetString("TargetTermstore", resourceCulture);
            }
        }
    }
}
