using System;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace CERTENROLLLib
{
	[System.Runtime.CompilerServices.CompilerGenerated, TypeIdentifier("728ab348-217d-11da-b2a4-000e7bbb2b09", "CERTENROLLLib.EncodingType")]
	public enum EncodingType
	{
		XCN_CRYPT_STRING_BASE64HEADER,
		XCN_CRYPT_STRING_BASE64,
		XCN_CRYPT_STRING_BINARY,
		XCN_CRYPT_STRING_BASE64REQUESTHEADER,
		XCN_CRYPT_STRING_HEX,
		XCN_CRYPT_STRING_HEXASCII,
		XCN_CRYPT_STRING_BASE64_ANY,
		XCN_CRYPT_STRING_ANY,
		XCN_CRYPT_STRING_HEX_ANY,
		XCN_CRYPT_STRING_BASE64X509CRLHEADER,
		XCN_CRYPT_STRING_HEXADDR,
		XCN_CRYPT_STRING_HEXASCIIADDR,
		XCN_CRYPT_STRING_HEXRAW,
		XCN_CRYPT_STRING_HASHDATA = 268435456,
		XCN_CRYPT_STRING_STRICT = 536870912,
		XCN_CRYPT_STRING_NOCRLF = 1073741824,
		XCN_CRYPT_STRING_NOCR = -2147483648
	}
}
