using System;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace CERTENROLLLib
{
	[System.Runtime.CompilerServices.CompilerGenerated, TypeIdentifier("728ab348-217d-11da-b2a4-000e7bbb2b09", "CERTENROLLLib.ObjectIdGroupId")]
	public enum ObjectIdGroupId
	{
		XCN_CRYPT_ANY_GROUP_ID,
		XCN_CRYPT_HASH_ALG_OID_GROUP_ID,
		XCN_CRYPT_ENCRYPT_ALG_OID_GROUP_ID,
		XCN_CRYPT_PUBKEY_ALG_OID_GROUP_ID,
		XCN_CRYPT_SIGN_ALG_OID_GROUP_ID,
		XCN_CRYPT_RDN_ATTR_OID_GROUP_ID,
		XCN_CRYPT_EXT_OR_ATTR_OID_GROUP_ID,
		XCN_CRYPT_ENHKEY_USAGE_OID_GROUP_ID,
		XCN_CRYPT_POLICY_OID_GROUP_ID,
		XCN_CRYPT_TEMPLATE_OID_GROUP_ID,
		XCN_CRYPT_LAST_OID_GROUP_ID,
		XCN_CRYPT_FIRST_ALG_OID_GROUP_ID = 1,
		XCN_CRYPT_LAST_ALG_OID_GROUP_ID = 4,
		XCN_CRYPT_GROUP_ID_MASK = 65535,
		XCN_CRYPT_OID_PREFER_CNG_ALGID_FLAG = 1073741824,
		XCN_CRYPT_OID_DISABLE_SEARCH_DS_FLAG = -2147483648,
		XCN_CRYPT_OID_INFO_OID_GROUP_BIT_LEN_MASK = 268369920,
		XCN_CRYPT_OID_INFO_OID_GROUP_BIT_LEN_SHIFT = 16,
		XCN_CRYPT_KEY_LENGTH_MASK = 268369920
	}
}
