using System.CodeDom.Compiler;
using System.ComponentModel;
using System.Diagnostics;
using System.Globalization;
using System.Resources;
using System.Runtime.CompilerServices;

namespace Metalogix.SharePoint.UI.WinForms.Properties
{
	[CompilerGenerated]
	[DebuggerNonUserCode]
	[GeneratedCode("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
	internal class Tooltips
	{
		private static ResourceManager resourceMan;

		private static CultureInfo resourceCulture;

		[EditorBrowsable(EditorBrowsableState.Advanced)]
		internal static CultureInfo Culture
		{
			get
			{
				return resourceCulture;
			}
			set
			{
				resourceCulture = value;
			}
		}

		internal static string MetalogixSharePointUIWinFormsAdministrationCreateSiteCollectionDialoghelpLinkHostHeader => ResourceManager.GetString("MetalogixSharePointUIWinFormsAdministrationCreateSiteCollectionDialoghelpLinkHostHeader", resourceCulture);

		internal static string MetalogixSharePointUIWinFormsAdministrationCreateSiteCollectionDialoghelpLinkHostHeaderLinkText => ResourceManager.GetString("MetalogixSharePointUIWinFormsAdministrationCreateSiteCollectionDialoghelpLinkHostHeaderLinkText", resourceCulture);

		internal static string MetalogixSharePointUIWinFormsAdministrationTCSharePointConnectionConfigw_comboAuthenticationType => ResourceManager.GetString("MetalogixSharePointUIWinFormsAdministrationTCSharePointConnectionConfigw_comboAuthenticationType", resourceCulture);

		internal static string MetalogixSharePointUIWinFormsAdministrationTCSharePointConnectionConfigw_comboAuthenticationTypeLinkText => ResourceManager.GetString("MetalogixSharePointUIWinFormsAdministrationTCSharePointConnectionConfigw_comboAuthenticationTypeLinkText", resourceCulture);

		internal static string MetalogixSharePointUIWinFormsAdministrationTCSharePointConnectionConfigw_comboConnectionType => ResourceManager.GetString("MetalogixSharePointUIWinFormsAdministrationTCSharePointConnectionConfigw_comboConnectionType", resourceCulture);

		internal static string MetalogixSharePointUIWinFormsAdministrationTCSharePointConnectionConfigw_comboConnectionTypeLinkText => ResourceManager.GetString("MetalogixSharePointUIWinFormsAdministrationTCSharePointConnectionConfigw_comboConnectionTypeLinkText", resourceCulture);

		internal static string MetalogixSharePointUIWinFormsAdministrationTCSharePointConnectionConfigw_lblTargetType => ResourceManager.GetString("MetalogixSharePointUIWinFormsAdministrationTCSharePointConnectionConfigw_lblTargetType", resourceCulture);

		internal static string MetalogixSharePointUIWinFormsAdministrationTCSharePointConnectionConfigw_lblTargetTypeLinkText => ResourceManager.GetString("MetalogixSharePointUIWinFormsAdministrationTCSharePointConnectionConfigw_lblTargetTypeLinkText", resourceCulture);

		internal static string MetalogixSharePointUIWinFormsExplorerViewOptionsShowListInternalNameOption => ResourceManager.GetString("MetalogixSharePointUIWinFormsExplorerViewOptionsShowListInternalNameOption", resourceCulture);

		internal static string MetalogixSharePointUIWinFormsExplorerViewOptionsShowWebUrlOption => ResourceManager.GetString("MetalogixSharePointUIWinFormsExplorerViewOptionsShowWebUrlOption", resourceCulture);

		internal static string MetalogixSharePointUIWinFormsExternalConnectionsManageNintexConnectionsSettings => ResourceManager.GetString("MetalogixSharePointUIWinFormsExternalConnectionsManageNintexConnectionsSettings", resourceCulture);

		internal static string MetalogixSharePointUIWinFormsMappingGlobalMappingsSetting => ResourceManager.GetString("MetalogixSharePointUIWinFormsMappingGlobalMappingsSetting", resourceCulture);

		internal static string MetalogixSharePointUIWinFormsMigrationBasicViewUserControlsTCAzureOptionsBasicViewtsAzureOption => ResourceManager.GetString("MetalogixSharePointUIWinFormsMigrationBasicViewUserControlsTCAzureOptionsBasicViewtsAzureOption", resourceCulture);

		internal static string MetalogixSharePointUIWinFormsMigrationBasicViewUserControlsTCAzureOptionsBasicViewtsEncryptAzureOption => ResourceManager.GetString("MetalogixSharePointUIWinFormsMigrationBasicViewUserControlsTCAzureOptionsBasicViewtsEncryptAzureOption", resourceCulture);

		internal static string MetalogixSharePointUIWinFormsMigrationBasicViewUserControlsTCExistingItemsBasicViewtsModifiedItems => ResourceManager.GetString("MetalogixSharePointUIWinFormsMigrationBasicViewUserControlsTCExistingItemsBasicViewtsModifiedItems", resourceCulture);

		internal static string MetalogixSharePointUIWinFormsMigrationBasicViewUserControlsTCExistingItemsBasicViewtsUpdateItems => ResourceManager.GetString("MetalogixSharePointUIWinFormsMigrationBasicViewUserControlsTCExistingItemsBasicViewtsUpdateItems", resourceCulture);

		internal static string MetalogixSharePointUIWinFormsMigrationBasicViewUserControlsTCExistingListsBasicViewtsModifiedLists => ResourceManager.GetString("MetalogixSharePointUIWinFormsMigrationBasicViewUserControlsTCExistingListsBasicViewtsModifiedLists", resourceCulture);

		internal static string MetalogixSharePointUIWinFormsMigrationBasicViewUserControlsTCExistingListsBasicViewtsUpdateLists => ResourceManager.GetString("MetalogixSharePointUIWinFormsMigrationBasicViewUserControlsTCExistingListsBasicViewtsUpdateLists", resourceCulture);

		internal static string MetalogixSharePointUIWinFormsMigrationBasicViewUserControlsTCExistingSitesBasicViewtsUpdateSites => ResourceManager.GetString("MetalogixSharePointUIWinFormsMigrationBasicViewUserControlsTCExistingSitesBasicViewtsUpdateSites", resourceCulture);

		internal static string MetalogixSharePointUIWinFormsMigrationBasicViewUserControlsTCGeneralOptionsBasicViewtsCorrectLinks => ResourceManager.GetString("MetalogixSharePointUIWinFormsMigrationBasicViewUserControlsTCGeneralOptionsBasicViewtsCorrectLinks", resourceCulture);

		internal static string MetalogixSharePointUIWinFormsMigrationBasicViewUserControlsTCGeneralOptionsBasicViewtsRenamedContentLinks => ResourceManager.GetString("MetalogixSharePointUIWinFormsMigrationBasicViewUserControlsTCGeneralOptionsBasicViewtsRenamedContentLinks", resourceCulture);

		internal static string MetalogixSharePointUIWinFormsMigrationBasicViewUserControlsTCGeneralOptionsBasicViewtsSendEmail => ResourceManager.GetString("MetalogixSharePointUIWinFormsMigrationBasicViewUserControlsTCGeneralOptionsBasicViewtsSendEmail", resourceCulture);

		internal static string MetalogixSharePointUIWinFormsMigrationBasicViewUserControlsTCGeneralOptionsBasicViewtsTextFieldLinks => ResourceManager.GetString("MetalogixSharePointUIWinFormsMigrationBasicViewUserControlsTCGeneralOptionsBasicViewtsTextFieldLinks", resourceCulture);

		internal static string MetalogixSharePointUIWinFormsMigrationBasicViewUserControlsTCListContentAdvancedOptionsBasicViewtsPreserveLibraryID => ResourceManager.GetString("MetalogixSharePointUIWinFormsMigrationBasicViewUserControlsTCListContentAdvancedOptionsBasicViewtsPreserveLibraryID", resourceCulture);

		internal static string MetalogixSharePointUIWinFormsMigrationBasicViewUserControlsTCListContentAdvancedOptionsBasicViewtsPreserveListID => ResourceManager.GetString("MetalogixSharePointUIWinFormsMigrationBasicViewUserControlsTCListContentAdvancedOptionsBasicViewtsPreserveListID", resourceCulture);

		internal static string MetalogixSharePointUIWinFormsMigrationBasicViewUserControlsTCListContentAdvancedOptionsBasicViewtsScanOfficeDocs => ResourceManager.GetString("MetalogixSharePointUIWinFormsMigrationBasicViewUserControlsTCListContentAdvancedOptionsBasicViewtsScanOfficeDocs", resourceCulture);

		internal static string MetalogixSharePointUIWinFormsMigrationBasicViewUserControlsTCListContentOptionsBasicViewtsCopyAllLists => ResourceManager.GetString("MetalogixSharePointUIWinFormsMigrationBasicViewUserControlsTCListContentOptionsBasicViewtsCopyAllLists", resourceCulture);

		internal static string MetalogixSharePointUIWinFormsMigrationBasicViewUserControlsTCListContentOptionsBasicViewtsCopyItemsDocuments => ResourceManager.GetString("MetalogixSharePointUIWinFormsMigrationBasicViewUserControlsTCListContentOptionsBasicViewtsCopyItemsDocuments", resourceCulture);

		internal static string MetalogixSharePointUIWinFormsMigrationBasicViewUserControlsTCListContentOptionsBasicViewtsCopyListItems => ResourceManager.GetString("MetalogixSharePointUIWinFormsMigrationBasicViewUserControlsTCListContentOptionsBasicViewtsCopyListItems", resourceCulture);

		internal static string MetalogixSharePointUIWinFormsMigrationBasicViewUserControlsTCListElementOptionsBasicViewbtnOpenUserMapping => ResourceManager.GetString("MetalogixSharePointUIWinFormsMigrationBasicViewUserControlsTCListElementOptionsBasicViewbtnOpenUserMapping", resourceCulture);

		internal static string MetalogixSharePointUIWinFormsMigrationBasicViewUserControlsTCListElementOptionsBasicViewtsCopyClosedWebParts => ResourceManager.GetString("MetalogixSharePointUIWinFormsMigrationBasicViewUserControlsTCListElementOptionsBasicViewtsCopyClosedWebParts", resourceCulture);

		internal static string MetalogixSharePointUIWinFormsMigrationBasicViewUserControlsTCListElementOptionsBasicViewtsCopyContentPermissions => ResourceManager.GetString("MetalogixSharePointUIWinFormsMigrationBasicViewUserControlsTCListElementOptionsBasicViewtsCopyContentPermissions", resourceCulture);

		internal static string MetalogixSharePointUIWinFormsMigrationBasicViewUserControlsTCListElementOptionsBasicViewtsCopyFolderPermissions => ResourceManager.GetString("MetalogixSharePointUIWinFormsMigrationBasicViewUserControlsTCListElementOptionsBasicViewtsCopyFolderPermissions", resourceCulture);

		internal static string MetalogixSharePointUIWinFormsMigrationBasicViewUserControlsTCListElementOptionsBasicViewtsCopyItemPermissions => ResourceManager.GetString("MetalogixSharePointUIWinFormsMigrationBasicViewUserControlsTCListElementOptionsBasicViewtsCopyItemPermissions", resourceCulture);

		internal static string MetalogixSharePointUIWinFormsMigrationBasicViewUserControlsTCListElementOptionsBasicViewtsCopyListPermissions => ResourceManager.GetString("MetalogixSharePointUIWinFormsMigrationBasicViewUserControlsTCListElementOptionsBasicViewtsCopyListPermissions", resourceCulture);

		internal static string MetalogixSharePointUIWinFormsMigrationBasicViewUserControlsTCListElementOptionsBasicViewtsCopySitePermissions => ResourceManager.GetString("MetalogixSharePointUIWinFormsMigrationBasicViewUserControlsTCListElementOptionsBasicViewtsCopySitePermissions", resourceCulture);

		internal static string MetalogixSharePointUIWinFormsMigrationBasicViewUserControlsTCListElementOptionsBasicViewtsCopyWebParts => ResourceManager.GetString("MetalogixSharePointUIWinFormsMigrationBasicViewUserControlsTCListElementOptionsBasicViewtsCopyWebParts", resourceCulture);

		internal static string MetalogixSharePointUIWinFormsMigrationBasicViewUserControlsTCListElementOptionsBasicViewtsFolderIgnorePermissions => ResourceManager.GetString("MetalogixSharePointUIWinFormsMigrationBasicViewUserControlsTCListElementOptionsBasicViewtsFolderIgnorePermissions", resourceCulture);

		internal static string MetalogixSharePointUIWinFormsMigrationBasicViewUserControlsTCListElementOptionsBasicViewtsIgnorePermissions => ResourceManager.GetString("MetalogixSharePointUIWinFormsMigrationBasicViewUserControlsTCListElementOptionsBasicViewtsIgnorePermissions", resourceCulture);

		internal static string MetalogixSharePointUIWinFormsMigrationBasicViewUserControlsTCListElementOptionsBasicViewtsItemIgnorePermissions => ResourceManager.GetString("MetalogixSharePointUIWinFormsMigrationBasicViewUserControlsTCListElementOptionsBasicViewtsItemIgnorePermissions", resourceCulture);

		internal static string MetalogixSharePointUIWinFormsMigrationBasicViewUserControlsTCListElementOptionsBasicViewtsMapGroupsByName => ResourceManager.GetString("MetalogixSharePointUIWinFormsMigrationBasicViewUserControlsTCListElementOptionsBasicViewtsMapGroupsByName", resourceCulture);

		internal static string MetalogixSharePointUIWinFormsMigrationBasicViewUserControlsTCListElementOptionsBasicViewtsMapMissingUsers => ResourceManager.GetString("MetalogixSharePointUIWinFormsMigrationBasicViewUserControlsTCListElementOptionsBasicViewtsMapMissingUsers", resourceCulture);

		internal static string MetalogixSharePointUIWinFormsMigrationBasicViewUserControlsTCListElementOptionsBasicViewtsMapMMD => ResourceManager.GetString("MetalogixSharePointUIWinFormsMigrationBasicViewUserControlsTCListElementOptionsBasicViewtsMapMMD", resourceCulture);

		internal static string MetalogixSharePointUIWinFormsMigrationBasicViewUserControlsTCListElementOptionsBasicViewtsMapPermissions => ResourceManager.GetString("MetalogixSharePointUIWinFormsMigrationBasicViewUserControlsTCListElementOptionsBasicViewtsMapPermissions", resourceCulture);

		internal static string MetalogixSharePointUIWinFormsMigrationBasicViewUserControlsTCListElementOptionsBasicViewtsMigrateBrokenSitePermissions => ResourceManager.GetString("MetalogixSharePointUIWinFormsMigrationBasicViewUserControlsTCListElementOptionsBasicViewtsMigrateBrokenSitePermissions", resourceCulture);

		internal static string MetalogixSharePointUIWinFormsMigrationBasicViewUserControlsTCListElementOptionsBasicViewtsOverwriteExistingGroups => ResourceManager.GetString("MetalogixSharePointUIWinFormsMigrationBasicViewUserControlsTCListElementOptionsBasicViewtsOverwriteExistingGroups", resourceCulture);

		internal static string MetalogixSharePointUIWinFormsMigrationBasicViewUserControlsTCListElementOptionsBasicViewtsPermissions => ResourceManager.GetString("MetalogixSharePointUIWinFormsMigrationBasicViewUserControlsTCListElementOptionsBasicViewtsPermissions", resourceCulture);

		internal static string MetalogixSharePointUIWinFormsMigrationBasicViewUserControlsTCListElementOptionsBasicViewtsWorkflow => ResourceManager.GetString("MetalogixSharePointUIWinFormsMigrationBasicViewUserControlsTCListElementOptionsBasicViewtsWorkflow", resourceCulture);

		internal static string MetalogixSharePointUIWinFormsMigrationBasicViewUserControlsTCListElementOptionsBasicViewtsWorkflowListScope => ResourceManager.GetString("MetalogixSharePointUIWinFormsMigrationBasicViewUserControlsTCListElementOptionsBasicViewtsWorkflowListScope", resourceCulture);

		internal static string MetalogixSharePointUIWinFormsMigrationBasicViewUserControlsTCSiteCollectionOptionsBasicViewcmbTemplate => ResourceManager.GetString("MetalogixSharePointUIWinFormsMigrationBasicViewUserControlsTCSiteCollectionOptionsBasicViewcmbTemplate", resourceCulture);

		internal static string MetalogixSharePointUIWinFormsMigrationBasicViewUserControlsTCSiteCollectionOptionsBasicViewcmbWebApplication => ResourceManager.GetString("MetalogixSharePointUIWinFormsMigrationBasicViewUserControlsTCSiteCollectionOptionsBasicViewcmbWebApplication", resourceCulture);

		internal static string MetalogixSharePointUIWinFormsMigrationBasicViewUserControlsTCSiteCollectionOptionsBasicViewlcAdvancedOptions => ResourceManager.GetString("MetalogixSharePointUIWinFormsMigrationBasicViewUserControlsTCSiteCollectionOptionsBasicViewlcAdvancedOptions", resourceCulture);

		internal static string MetalogixSharePointUIWinFormsMigrationBasicViewUserControlsTCSiteCollectionOptionsBasicViewtESiteCollectionAdministrator => ResourceManager.GetString("MetalogixSharePointUIWinFormsMigrationBasicViewUserControlsTCSiteCollectionOptionsBasicViewtESiteCollectionAdministrator", resourceCulture);

		internal static string MetalogixSharePointUIWinFormsMigrationBasicViewUserControlsTCSiteCollectionOptionsBasicViewtETargetSiteUrl => ResourceManager.GetString("MetalogixSharePointUIWinFormsMigrationBasicViewUserControlsTCSiteCollectionOptionsBasicViewtETargetSiteUrl", resourceCulture);

		internal static string MetalogixSharePointUIWinFormsMigrationBasicViewUserControlsTCSiteCollectionOptionsBasicViewtsCopyAuditSettings => ResourceManager.GetString("MetalogixSharePointUIWinFormsMigrationBasicViewUserControlsTCSiteCollectionOptionsBasicViewtsCopyAuditSettings", resourceCulture);

		internal static string MetalogixSharePointUIWinFormsMigrationBasicViewUserControlsTCSiteCollectionOptionsBasicViewtsCopyListTemplateGallery => ResourceManager.GetString("MetalogixSharePointUIWinFormsMigrationBasicViewUserControlsTCSiteCollectionOptionsBasicViewtsCopyListTemplateGallery", resourceCulture);

		internal static string MetalogixSharePointUIWinFormsMigrationBasicViewUserControlsTCSiteCollectionOptionsBasicViewtsCopyMasterPageGallery => ResourceManager.GetString("MetalogixSharePointUIWinFormsMigrationBasicViewUserControlsTCSiteCollectionOptionsBasicViewtsCopyMasterPageGallery", resourceCulture);

		internal static string MetalogixSharePointUIWinFormsMigrationBasicViewUserControlsTCSiteCollectionOptionsBasicViewtsCopySiteCollectionAdmin => ResourceManager.GetString("MetalogixSharePointUIWinFormsMigrationBasicViewUserControlsTCSiteCollectionOptionsBasicViewtsCopySiteCollectionAdmin", resourceCulture);

		internal static string MetalogixSharePointUIWinFormsMigrationBasicViewUserControlsTCSiteCollectionOptionsBasicViewtsSetSiteQuota => ResourceManager.GetString("MetalogixSharePointUIWinFormsMigrationBasicViewUserControlsTCSiteCollectionOptionsBasicViewtsSetSiteQuota", resourceCulture);

		internal static string MetalogixSharePointUIWinFormsMigrationBasicViewUserControlsTCSiteOptionsBasicViewtsCopyChildSites => ResourceManager.GetString("MetalogixSharePointUIWinFormsMigrationBasicViewUserControlsTCSiteOptionsBasicViewtsCopyChildSites", resourceCulture);

		internal static string MetalogixSharePointUIWinFormsMigrationBasicViewUserControlsTCSiteOptionsBasicViewtsCopyNavigation => ResourceManager.GetString("MetalogixSharePointUIWinFormsMigrationBasicViewUserControlsTCSiteOptionsBasicViewtsCopyNavigation", resourceCulture);

		internal static string MetalogixSharePointUIWinFormsMigrationBasicViewUserControlsTCSiteOptionsBasicViewtsCopySiteFeatures => ResourceManager.GetString("MetalogixSharePointUIWinFormsMigrationBasicViewUserControlsTCSiteOptionsBasicViewtsCopySiteFeatures", resourceCulture);

		internal static string MetalogixSharePointUIWinFormsMigrationTCFolderContentOptions_cbUseAzureUpload => ResourceManager.GetString("MetalogixSharePointUIWinFormsMigrationTCFolderContentOptions_cbUseAzureUpload", resourceCulture);

		internal static string MetalogixSharePointUIWinFormsMigrationTCFolderContentOptions_cbUseAzureUploadLinkText => ResourceManager.GetString("MetalogixSharePointUIWinFormsMigrationTCFolderContentOptions_cbUseAzureUploadLinkText", resourceCulture);

		internal static string MetalogixSharePointUIWinFormsMigrationTCGeneralOptionsw_cbComprehensiveLinkCorrection => ResourceManager.GetString("MetalogixSharePointUIWinFormsMigrationTCGeneralOptionsw_cbComprehensiveLinkCorrection", resourceCulture);

		internal static string MetalogixSharePointUIWinFormsMigrationTCGeneralOptionsw_cbComprehensiveLinkCorrectionLinkText => ResourceManager.GetString("MetalogixSharePointUIWinFormsMigrationTCGeneralOptionsw_cbComprehensiveLinkCorrectionLinkText", resourceCulture);

		internal static string MetalogixSharePointUIWinFormsMigrationTCGeneralOptionsw_cbCorrectLinks => ResourceManager.GetString("MetalogixSharePointUIWinFormsMigrationTCGeneralOptionsw_cbCorrectLinks", resourceCulture);

		internal static string MetalogixSharePointUIWinFormsMigrationTCGeneralOptionsw_cbCorrectLinksLinkText => ResourceManager.GetString("MetalogixSharePointUIWinFormsMigrationTCGeneralOptionsw_cbCorrectLinksLinkText", resourceCulture);

		internal static string MetalogixSharePointUIWinFormsMigrationTCGeneralOptionsw_cbForceRefresh => ResourceManager.GetString("MetalogixSharePointUIWinFormsMigrationTCGeneralOptionsw_cbForceRefresh", resourceCulture);

		internal static string MetalogixSharePointUIWinFormsMigrationTCGeneralOptionsw_cbForceRefreshLinkText => ResourceManager.GetString("MetalogixSharePointUIWinFormsMigrationTCGeneralOptionsw_cbForceRefreshLinkText", resourceCulture);

		internal static string MetalogixSharePointUIWinFormsMigrationTCGeneralOptionsw_cbVerbose => ResourceManager.GetString("MetalogixSharePointUIWinFormsMigrationTCGeneralOptionsw_cbVerbose", resourceCulture);

		internal static string MetalogixSharePointUIWinFormsMigrationTCGeneralOptionsw_cbVerboseLinkText => ResourceManager.GetString("MetalogixSharePointUIWinFormsMigrationTCGeneralOptionsw_cbVerboseLinkText", resourceCulture);

		internal static string MetalogixSharePointUIWinFormsMigrationTCListContentOptions_cbUseAzureUpload => ResourceManager.GetString("MetalogixSharePointUIWinFormsMigrationTCListContentOptions_cbUseAzureUpload", resourceCulture);

		internal static string MetalogixSharePointUIWinFormsMigrationTCListContentOptions_cbUseAzureUploadLinkText => ResourceManager.GetString("MetalogixSharePointUIWinFormsMigrationTCListContentOptions_cbUseAzureUploadLinkText", resourceCulture);

		internal static string MetalogixSharePointUIWinFormsMigrationTCListContentOptionsw_cbApplyDocumentSets => ResourceManager.GetString("MetalogixSharePointUIWinFormsMigrationTCListContentOptionsw_cbApplyDocumentSets", resourceCulture);

		internal static string MetalogixSharePointUIWinFormsMigrationTCListContentOptionsw_cbApplyDocumentSetsLinkText => ResourceManager.GetString("MetalogixSharePointUIWinFormsMigrationTCListContentOptionsw_cbApplyDocumentSetsLinkText", resourceCulture);

		internal static string MetalogixSharePointUIWinFormsMigrationTCListContentOptionsw_cbDisableParsing => ResourceManager.GetString("MetalogixSharePointUIWinFormsMigrationTCListContentOptionsw_cbDisableParsing", resourceCulture);

		internal static string MetalogixSharePointUIWinFormsMigrationTCListContentOptionsw_cbDisableParsingLinkText => ResourceManager.GetString("MetalogixSharePointUIWinFormsMigrationTCListContentOptionsw_cbDisableParsingLinkText", resourceCulture);

		internal static string MetalogixSharePointUIWinFormsMigrationTCListContentOptionsw_cbPreserveDocumentIDs => ResourceManager.GetString("MetalogixSharePointUIWinFormsMigrationTCListContentOptionsw_cbPreserveDocumentIDs", resourceCulture);

		internal static string MetalogixSharePointUIWinFormsMigrationTCListContentOptionsw_cbPreserveDocumentIDsLinkText => ResourceManager.GetString("MetalogixSharePointUIWinFormsMigrationTCListContentOptionsw_cbPreserveDocumentIDsLinkText", resourceCulture);

		internal static string MetalogixSharePointUIWinFormsMigrationTCListContentOptionsw_cbPreserveIds => ResourceManager.GetString("MetalogixSharePointUIWinFormsMigrationTCListContentOptionsw_cbPreserveIds", resourceCulture);

		internal static string MetalogixSharePointUIWinFormsMigrationTCListContentOptionsw_cbPreserveIdsLinkText => ResourceManager.GetString("MetalogixSharePointUIWinFormsMigrationTCListContentOptionsw_cbPreserveIdsLinkText", resourceCulture);

		internal static string MetalogixSharePointUIWinFormsMigrationTCListContentOptionsw_cbPreserveSharePointDocumentIDs => ResourceManager.GetString("MetalogixSharePointUIWinFormsMigrationTCListContentOptionsw_cbPreserveSharePointDocumentIDs", resourceCulture);

		internal static string MetalogixSharePointUIWinFormsMigrationTCListContentOptionsw_cbPreserveSharePointDocumentIDsLinkText => ResourceManager.GetString("MetalogixSharePointUIWinFormsMigrationTCListContentOptionsw_cbPreserveSharePointDocumentIDsLinkText", resourceCulture);

		internal static string MetalogixSharePointUIWinFormsMigrationTCListContentOptionsw_cbReattachPageLayouts => ResourceManager.GetString("MetalogixSharePointUIWinFormsMigrationTCListContentOptionsw_cbReattachPageLayouts", resourceCulture);

		internal static string MetalogixSharePointUIWinFormsMigrationTCListContentOptionsw_cbReattachPageLayoutsLinkText => ResourceManager.GetString("MetalogixSharePointUIWinFormsMigrationTCListContentOptionsw_cbReattachPageLayoutsLinkText", resourceCulture);

		internal static string MetalogixSharePointUIWinFormsMigrationTCMappingOptionsw_btnEditGlobalMappings => ResourceManager.GetString("MetalogixSharePointUIWinFormsMigrationTCMappingOptionsw_btnEditGlobalMappings", resourceCulture);

		internal static string MetalogixSharePointUIWinFormsMigrationTCMappingOptionsw_btnEditGlobalMappingsLinkText => ResourceManager.GetString("MetalogixSharePointUIWinFormsMigrationTCMappingOptionsw_btnEditGlobalMappingsLinkText", resourceCulture);

		internal static string MetalogixSharePointUIWinFormsMigrationTCMappingOptionsw_cbAllowDBWrite => ResourceManager.GetString("MetalogixSharePointUIWinFormsMigrationTCMappingOptionsw_cbAllowDBWrite", resourceCulture);

		internal static string MetalogixSharePointUIWinFormsMigrationTCMappingOptionsw_cbAllowDBWriteLinkText => ResourceManager.GetString("MetalogixSharePointUIWinFormsMigrationTCMappingOptionsw_cbAllowDBWriteLinkText", resourceCulture);

		internal static string MetalogixSharePointUIWinFormsMigrationTCMappingOptionsw_cbMissingUsers => ResourceManager.GetString("MetalogixSharePointUIWinFormsMigrationTCMappingOptionsw_cbMissingUsers", resourceCulture);

		internal static string MetalogixSharePointUIWinFormsMigrationTCMappingOptionsw_cbMissingUsersLinkText => ResourceManager.GetString("MetalogixSharePointUIWinFormsMigrationTCMappingOptionsw_cbMissingUsersLinkText", resourceCulture);

		internal static string MetalogixSharePointUIWinFormsMigrationTCMigrationModeOptionsw_cbPropagateItemDeletions => ResourceManager.GetString("MetalogixSharePointUIWinFormsMigrationTCMigrationModeOptionsw_cbPropagateItemDeletions", resourceCulture);

		internal static string MetalogixSharePointUIWinFormsMigrationTCMigrationModeOptionsw_cbPropagateItemDeletionsLinkText => ResourceManager.GetString("MetalogixSharePointUIWinFormsMigrationTCMigrationModeOptionsw_cbPropagateItemDeletionsLinkText", resourceCulture);

		internal static string MetalogixSharePointUIWinFormsMigrationTCMigrationModeOptionsw_cbUpdateItems => ResourceManager.GetString("MetalogixSharePointUIWinFormsMigrationTCMigrationModeOptionsw_cbUpdateItems", resourceCulture);

		internal static string MetalogixSharePointUIWinFormsMigrationTCMigrationModeOptionsw_cbUpdateItemsLinkText => ResourceManager.GetString("MetalogixSharePointUIWinFormsMigrationTCMigrationModeOptionsw_cbUpdateItemsLinkText", resourceCulture);

		internal static string MetalogixSharePointUIWinFormsMigrationTCMigrationModeOptionsw_cbUpdateLists => ResourceManager.GetString("MetalogixSharePointUIWinFormsMigrationTCMigrationModeOptionsw_cbUpdateLists", resourceCulture);

		internal static string MetalogixSharePointUIWinFormsMigrationTCMigrationModeOptionsw_cbUpdateListsLinkText => ResourceManager.GetString("MetalogixSharePointUIWinFormsMigrationTCMigrationModeOptionsw_cbUpdateListsLinkText", resourceCulture);

		internal static string MetalogixSharePointUIWinFormsMigrationTCMigrationModeOptionsw_rbCustomMode => ResourceManager.GetString("MetalogixSharePointUIWinFormsMigrationTCMigrationModeOptionsw_rbCustomMode", resourceCulture);

		internal static string MetalogixSharePointUIWinFormsMigrationTCMigrationModeOptionsw_rbCustomModeLinkText => ResourceManager.GetString("MetalogixSharePointUIWinFormsMigrationTCMigrationModeOptionsw_rbCustomModeLinkText", resourceCulture);

		internal static string MetalogixSharePointUIWinFormsMigrationTCNavigationOptionsw_rbCopyOnlyQuickLaunch => ResourceManager.GetString("MetalogixSharePointUIWinFormsMigrationTCNavigationOptionsw_rbCopyOnlyQuickLaunch", resourceCulture);

		internal static string MetalogixSharePointUIWinFormsMigrationTCNavigationOptionsw_rbCopyOnlyQuickLaunchLinkText => ResourceManager.GetString("MetalogixSharePointUIWinFormsMigrationTCNavigationOptionsw_rbCopyOnlyQuickLaunchLinkText", resourceCulture);

		internal static string MetalogixSharePointUIWinFormsMigrationTCSiteCollectionOptionshelpLinkHostHeader => ResourceManager.GetString("MetalogixSharePointUIWinFormsMigrationTCSiteCollectionOptionshelpLinkHostHeader", resourceCulture);

		internal static string MetalogixSharePointUIWinFormsMigrationTCSiteCollectionOptionshelpLinkHostHeaderLinkText => ResourceManager.GetString("MetalogixSharePointUIWinFormsMigrationTCSiteCollectionOptionshelpLinkHostHeaderLinkText", resourceCulture);

		internal static string MetalogixSharePointUIWinFormsMigrationTCSiteCollectionOptionsw_cbCopyAuditSettings => ResourceManager.GetString("MetalogixSharePointUIWinFormsMigrationTCSiteCollectionOptionsw_cbCopyAuditSettings", resourceCulture);

		internal static string MetalogixSharePointUIWinFormsMigrationTCSiteCollectionOptionsw_cbCopyAuditSettingsLinkText => ResourceManager.GetString("MetalogixSharePointUIWinFormsMigrationTCSiteCollectionOptionsw_cbCopyAuditSettingsLinkText", resourceCulture);

		internal static string MetalogixSharePointUIWinFormsMigrationTCSiteCollectionOptionsw_cbCopyMasterPageGallery => ResourceManager.GetString("MetalogixSharePointUIWinFormsMigrationTCSiteCollectionOptionsw_cbCopyMasterPageGallery", resourceCulture);

		internal static string MetalogixSharePointUIWinFormsMigrationTCSiteCollectionOptionsw_cbCopyMasterPageGalleryLinkText => ResourceManager.GetString("MetalogixSharePointUIWinFormsMigrationTCSiteCollectionOptionsw_cbCopyMasterPageGalleryLinkText", resourceCulture);

		internal static string MetalogixSharePointUIWinFormsMigrationTCSiteContentOptionsw_cbApplyTheme => ResourceManager.GetString("MetalogixSharePointUIWinFormsMigrationTCSiteContentOptionsw_cbApplyTheme", resourceCulture);

		internal static string MetalogixSharePointUIWinFormsMigrationTCSiteContentOptionsw_cbApplyThemeLinkText => ResourceManager.GetString("MetalogixSharePointUIWinFormsMigrationTCSiteContentOptionsw_cbApplyThemeLinkText", resourceCulture);

		internal static string MetalogixSharePointUIWinFormsMigrationTCSiteContentOptionsw_cbCopySubsites => ResourceManager.GetString("MetalogixSharePointUIWinFormsMigrationTCSiteContentOptionsw_cbCopySubsites", resourceCulture);

		internal static string MetalogixSharePointUIWinFormsMigrationTCSiteContentOptionsw_cbCopySubsitesLinkText => ResourceManager.GetString("MetalogixSharePointUIWinFormsMigrationTCSiteContentOptionsw_cbCopySubsitesLinkText", resourceCulture);

		internal static string MetalogixSharePointUIWinFormsMigrationTCSiteContentOptionsw_rbClearTargetFeatures => ResourceManager.GetString("MetalogixSharePointUIWinFormsMigrationTCSiteContentOptionsw_rbClearTargetFeatures", resourceCulture);

		internal static string MetalogixSharePointUIWinFormsMigrationTCSiteContentOptionsw_rbClearTargetFeaturesLinkText => ResourceManager.GetString("MetalogixSharePointUIWinFormsMigrationTCSiteContentOptionsw_rbClearTargetFeaturesLinkText", resourceCulture);

		internal static string MetalogixSharePointUIWinFormsMigrationTCSiteContentOptionsw_rbCopyOnlyQuickLaunch => ResourceManager.GetString("MetalogixSharePointUIWinFormsMigrationTCSiteContentOptionsw_rbCopyOnlyQuickLaunch", resourceCulture);

		internal static string MetalogixSharePointUIWinFormsMigrationTCSiteContentOptionsw_rbCopyOnlyQuickLaunchLinkText => ResourceManager.GetString("MetalogixSharePointUIWinFormsMigrationTCSiteContentOptionsw_rbCopyOnlyQuickLaunchLinkText", resourceCulture);

		internal static string MetalogixSharePointUIWinFormsMigrationTCSiteContentOptionsw_rbPreserveOnTarget => ResourceManager.GetString("MetalogixSharePointUIWinFormsMigrationTCSiteContentOptionsw_rbPreserveOnTarget", resourceCulture);

		internal static string MetalogixSharePointUIWinFormsMigrationTCSiteContentOptionsw_rbPreserveOnTargetLinkText => ResourceManager.GetString("MetalogixSharePointUIWinFormsMigrationTCSiteContentOptionsw_rbPreserveOnTargetLinkText", resourceCulture);

		internal static string MetalogixSharePointUIWinFormsMigrationTCStoragePointOptionsMMSw_rbShallowCopyExternalizedData => ResourceManager.GetString("MetalogixSharePointUIWinFormsMigrationTCStoragePointOptionsMMSw_rbShallowCopyExternalizedData", resourceCulture);

		internal static string MetalogixSharePointUIWinFormsMigrationTCStoragePointOptionsMMSw_rbShallowCopyExternalizedDataLinkText => ResourceManager.GetString("MetalogixSharePointUIWinFormsMigrationTCStoragePointOptionsMMSw_rbShallowCopyExternalizedDataLinkText", resourceCulture);

		internal static string MetalogixSharePointUIWinFormsMigrationTCStoragePointOptionsMMSw_rbSideloadDocs => ResourceManager.GetString("MetalogixSharePointUIWinFormsMigrationTCStoragePointOptionsMMSw_rbSideloadDocs", resourceCulture);

		internal static string MetalogixSharePointUIWinFormsMigrationTCStoragePointOptionsMMSw_rbSideloadDocsLinkText => ResourceManager.GetString("MetalogixSharePointUIWinFormsMigrationTCStoragePointOptionsMMSw_rbSideloadDocsLinkText", resourceCulture);

		internal static string MetalogixSharePointUIWinFormsMigrationTCStoragePointOptionsw_cbSideloadDocs => ResourceManager.GetString("MetalogixSharePointUIWinFormsMigrationTCStoragePointOptionsw_cbSideloadDocs", resourceCulture);

		internal static string MetalogixSharePointUIWinFormsMigrationTCStoragePointOptionsw_cbSideloadDocsLinkText => ResourceManager.GetString("MetalogixSharePointUIWinFormsMigrationTCStoragePointOptionsw_cbSideloadDocsLinkText", resourceCulture);

		internal static string MetalogixSharePointUIWinFormsMigrationTCTaxonomyOptions_cbResolveByName => ResourceManager.GetString("MetalogixSharePointUIWinFormsMigrationTCTaxonomyOptions_cbResolveByName", resourceCulture);

		internal static string MetalogixSharePointUIWinFormsMigrationTCTaxonomyOptions_cbResolveByNameLinkText => ResourceManager.GetString("MetalogixSharePointUIWinFormsMigrationTCTaxonomyOptions_cbResolveByNameLinkText", resourceCulture);

		internal static string MetalogixSharePointUIWinFormsMigrationTCTaxonomyOptionscbTransformField => ResourceManager.GetString("MetalogixSharePointUIWinFormsMigrationTCTaxonomyOptionscbTransformField", resourceCulture);

		internal static string MetalogixSharePointUIWinFormsMigrationTCTaxonomyOptionscbTransformFieldLinkText => ResourceManager.GetString("MetalogixSharePointUIWinFormsMigrationTCTaxonomyOptionscbTransformFieldLinkText", resourceCulture);

		internal static string MetalogixSharePointUIWinFormsMigrationTCTaxonomyOptionscbTransformSiteColumns => ResourceManager.GetString("MetalogixSharePointUIWinFormsMigrationTCTaxonomyOptionscbTransformSiteColumns", resourceCulture);

		internal static string MetalogixSharePointUIWinFormsMigrationTCTaxonomyOptionscbTransformSiteColumnsLinkText => ResourceManager.GetString("MetalogixSharePointUIWinFormsMigrationTCTaxonomyOptionscbTransformSiteColumnsLinkText", resourceCulture);

		internal static string MetalogixSharePointUIWinFormsMigrationTCTaxonomyOptionsw_cbCopyReferencedManagedMetadata => ResourceManager.GetString("MetalogixSharePointUIWinFormsMigrationTCTaxonomyOptionsw_cbCopyReferencedManagedMetadata", resourceCulture);

		internal static string MetalogixSharePointUIWinFormsMigrationTCTaxonomyOptionsw_cbCopyReferencedManagedMetadataLinkText => ResourceManager.GetString("MetalogixSharePointUIWinFormsMigrationTCTaxonomyOptionsw_cbCopyReferencedManagedMetadataLinkText", resourceCulture);

		internal static string MetalogixSharePointUIWinFormsMigrationTCTaxonomyOptionsw_cbMapTermStores => ResourceManager.GetString("MetalogixSharePointUIWinFormsMigrationTCTaxonomyOptionsw_cbMapTermStores", resourceCulture);

		internal static string MetalogixSharePointUIWinFormsMigrationTCTaxonomyOptionsw_cbMapTermStoresLinkText => ResourceManager.GetString("MetalogixSharePointUIWinFormsMigrationTCTaxonomyOptionsw_cbMapTermStoresLinkText", resourceCulture);

		internal static string MetalogixSharePointUIWinFormsMigrationTCWebPartsOptionsw_cbCopyContentZoneContent => ResourceManager.GetString("MetalogixSharePointUIWinFormsMigrationTCWebPartsOptionsw_cbCopyContentZoneContent", resourceCulture);

		internal static string MetalogixSharePointUIWinFormsMigrationTCWebPartsOptionsw_cbCopyContentZoneContentLinkText => ResourceManager.GetString("MetalogixSharePointUIWinFormsMigrationTCWebPartsOptionsw_cbCopyContentZoneContentLinkText", resourceCulture);

		internal static string MetalogixSharePointUIWinFormsMigrationTCWebPartsOptionsw_cbFormWebParts => ResourceManager.GetString("MetalogixSharePointUIWinFormsMigrationTCWebPartsOptionsw_cbFormWebParts", resourceCulture);

		internal static string MetalogixSharePointUIWinFormsMigrationTCWebPartsOptionsw_cbFormWebPartsLinkText => ResourceManager.GetString("MetalogixSharePointUIWinFormsMigrationTCWebPartsOptionsw_cbFormWebPartsLinkText", resourceCulture);

		internal static string MetalogixSharePointUIWinFormsMigrationTCWorkflowOptionshelpIncludePreviousVersionInstancesButton => ResourceManager.GetString("MetalogixSharePointUIWinFormsMigrationTCWorkflowOptionshelpIncludePreviousVersionInstancesButton", resourceCulture);

		internal static string MetalogixSharePointUIWinFormsMigrationTCWorkflowOptionshelpIncludePreviousVersionInstancesButtonLinkText => ResourceManager.GetString("MetalogixSharePointUIWinFormsMigrationTCWorkflowOptionshelpIncludePreviousVersionInstancesButtonLinkText", resourceCulture);

		internal static string MetalogixSharePointUIWinFormsMigrationTCWorkflowOptionshelpListSPD2013OMButton => ResourceManager.GetString("MetalogixSharePointUIWinFormsMigrationTCWorkflowOptionshelpListSPD2013OMButton", resourceCulture);

		internal static string MetalogixSharePointUIWinFormsMigrationTCWorkflowOptionshelpListSPD2013OMButtonLinkText => ResourceManager.GetString("MetalogixSharePointUIWinFormsMigrationTCWorkflowOptionshelpListSPD2013OMButtonLinkText", resourceCulture);

		internal static string MetalogixSharePointUIWinFormsMigrationTCWorkflowOptionshelpWebSPD2013OMButton => ResourceManager.GetString("MetalogixSharePointUIWinFormsMigrationTCWorkflowOptionshelpWebSPD2013OMButton", resourceCulture);

		internal static string MetalogixSharePointUIWinFormsMigrationTCWorkflowOptionshelpWebSPD2013OMButtonLinkText => ResourceManager.GetString("MetalogixSharePointUIWinFormsMigrationTCWorkflowOptionshelpWebSPD2013OMButtonLinkText", resourceCulture);

		internal static string MetalogixSharePointUIWinFormsTransformFieldToManagedMetadataConfigItemDialog_cbCreateNewField => ResourceManager.GetString("MetalogixSharePointUIWinFormsTransformFieldToManagedMetadataConfigItemDialog_cbCreateNewField", resourceCulture);

		internal static string MetalogixSharePointUIWinFormsTransformFieldToManagedMetadataConfigItemDialog_cbCreateNewFieldLinkText => ResourceManager.GetString("MetalogixSharePointUIWinFormsTransformFieldToManagedMetadataConfigItemDialog_cbCreateNewFieldLinkText", resourceCulture);

		internal static string MetalogixSharePointUIWinFormsTransformFieldToManagedMetadataConfigItemDialog_cbGroup => ResourceManager.GetString("MetalogixSharePointUIWinFormsTransformFieldToManagedMetadataConfigItemDialog_cbGroup", resourceCulture);

		internal static string MetalogixSharePointUIWinFormsTransformFieldToManagedMetadataConfigItemDialog_cbGroupLinkText => ResourceManager.GetString("MetalogixSharePointUIWinFormsTransformFieldToManagedMetadataConfigItemDialog_cbGroupLinkText", resourceCulture);

		internal static string MetalogixSharePointUIWinFormsTransformFieldToManagedMetadataConfigItemDialog_cbTermSet => ResourceManager.GetString("MetalogixSharePointUIWinFormsTransformFieldToManagedMetadataConfigItemDialog_cbTermSet", resourceCulture);

		internal static string MetalogixSharePointUIWinFormsTransformFieldToManagedMetadataConfigItemDialog_cbTermSetLinkText => ResourceManager.GetString("MetalogixSharePointUIWinFormsTransformFieldToManagedMetadataConfigItemDialog_cbTermSetLinkText", resourceCulture);

		internal static string MetalogixSharePointUIWinFormsTransformFieldToManagedMetadataConfigItemDialog_txtAnchor => ResourceManager.GetString("MetalogixSharePointUIWinFormsTransformFieldToManagedMetadataConfigItemDialog_txtAnchor", resourceCulture);

		internal static string MetalogixSharePointUIWinFormsTransformFieldToManagedMetadataConfigItemDialog_txtAnchorLinkText => ResourceManager.GetString("MetalogixSharePointUIWinFormsTransformFieldToManagedMetadataConfigItemDialog_txtAnchorLinkText", resourceCulture);

		internal static string MetalogixSharePointUIWinFormsTransformSiteColumnToManagedMetadataConfigItemDialog_cbCreateNewField => ResourceManager.GetString("MetalogixSharePointUIWinFormsTransformSiteColumnToManagedMetadataConfigItemDialog_cbCreateNewField", resourceCulture);

		internal static string MetalogixSharePointUIWinFormsTransformSiteColumnToManagedMetadataConfigItemDialog_cbCreateNewFieldLinkText => ResourceManager.GetString("MetalogixSharePointUIWinFormsTransformSiteColumnToManagedMetadataConfigItemDialog_cbCreateNewFieldLinkText", resourceCulture);

		internal static string MetalogixSharePointUIWinFormsTransformSiteColumnToManagedMetadataConfigItemDialog_cbGroup => ResourceManager.GetString("MetalogixSharePointUIWinFormsTransformSiteColumnToManagedMetadataConfigItemDialog_cbGroup", resourceCulture);

		internal static string MetalogixSharePointUIWinFormsTransformSiteColumnToManagedMetadataConfigItemDialog_cbGroupLinkText => ResourceManager.GetString("MetalogixSharePointUIWinFormsTransformSiteColumnToManagedMetadataConfigItemDialog_cbGroupLinkText", resourceCulture);

		internal static string MetalogixSharePointUIWinFormsTransformSiteColumnToManagedMetadataConfigItemDialog_cbTermSet => ResourceManager.GetString("MetalogixSharePointUIWinFormsTransformSiteColumnToManagedMetadataConfigItemDialog_cbTermSet", resourceCulture);

		internal static string MetalogixSharePointUIWinFormsTransformSiteColumnToManagedMetadataConfigItemDialog_cbTermSetLinkText => ResourceManager.GetString("MetalogixSharePointUIWinFormsTransformSiteColumnToManagedMetadataConfigItemDialog_cbTermSetLinkText", resourceCulture);

		internal static string MetalogixSharePointUIWinFormsTransformSiteColumnToManagedMetadataConfigItemDialog_txtAnchor => ResourceManager.GetString("MetalogixSharePointUIWinFormsTransformSiteColumnToManagedMetadataConfigItemDialog_txtAnchor", resourceCulture);

		internal static string MetalogixSharePointUIWinFormsTransformSiteColumnToManagedMetadataConfigItemDialog_txtAnchorLinkText => ResourceManager.GetString("MetalogixSharePointUIWinFormsTransformSiteColumnToManagedMetadataConfigItemDialog_txtAnchorLinkText", resourceCulture);

		[EditorBrowsable(EditorBrowsableState.Advanced)]
		internal static ResourceManager ResourceManager
		{
			get
			{
				if (resourceMan == null)
				{
					resourceMan = new ResourceManager("Metalogix.SharePoint.UI.WinForms.Properties.Tooltips", typeof(Tooltips).Assembly);
				}
				return resourceMan;
			}
		}

		internal Tooltips()
		{
		}
	}
}
