//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Metalogix.SharePoint.Adapters.NWS.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Metalogix.SharePoint.Adapters.NWS.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to determine root folder of list. This may be because the list lacks a valid default view..
        /// </summary>
        public static string Error_unable_to_determine_list_root_folder {
            get {
                return ResourceManager.GetString("Error_unable_to_determine_list_root_folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to read web part &apos;{0}&apos; from page &apos;{1}&apos;: {2}.
        /// </summary>
        public static string FailedToReadSpecificWebPartFromPage {
            get {
                return ResourceManager.GetString("FailedToReadSpecificWebPartFromPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The SharePoint Client Side Object Model 2013 adapter cannot be used to connect to older versions of SharePoint. Connecting to older versions requires using the Native Web Services adapter..
        /// </summary>
        public static string Older_SharePoint_Detected {
            get {
                return ResourceManager.GetString("Older_SharePoint_Detected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The page layout for this publishing page has not yet been created. Please make sure that all features associated with this site template have been enabled and attempt this web part copy again. This most commonly occurs for News sites which need the &quot;Office SharePoint Server Standard Site Collection features&quot; feature enabled..
        /// </summary>
        public static string PageLayoutNotCreatedFromTemplateError {
            get {
                return ResourceManager.GetString("PageLayoutNotCreatedFromTemplateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to obtain SharePoint Online authentication cookie. No result was returned..
        /// </summary>
        public static string SharePoint_Online_Empty_Cookie {
            get {
                return ResourceManager.GetString("SharePoint_Online_Empty_Cookie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Native Web Services cannot be used to connect to SharePoint 2013. Connecting to SharePoint 2013 requires using the SharePoint Client Side Object Model 2013 adapter type..
        /// </summary>
        public static string SharePoint2013_Detected {
            get {
                return ResourceManager.GetString("SharePoint2013_Detected", resourceCulture);
            }
        }
    }
}
